# Generated by Django 4.2.7 on 2023-11-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("expense_concept", "0001_initial"),
        ("cost_center", "0001_initial"),
        ("business_unit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetDescription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("description", models.TextField(help_text="Description", verbose_name="Description")),
                (
                    "expense_concept",
                    models.ForeignKey(
                        help_text="Expense concept",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_concepts_budgets",
                        to="expense_concept.expenseconcept",
                        verbose_name="Expense concept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Description",
                "verbose_name_plural": "Budget Descriptions",
            },
        ),
        migrations.CreateModel(
            name="BudgetCap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("cap", models.FloatField(default=0, help_text="Cap", verbose_name="Cap")),
                ("description", models.TextField(help_text="Description", verbose_name="Description")),
                (
                    "business_unit",
                    models.ForeignKey(
                        help_text="Business unit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_unit_budget_caps",
                        to="business_unit.businessunit",
                        verbose_name="Business unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Cap",
                "verbose_name_plural": "Budget Caps",
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("unit_value", models.FloatField(default=0, help_text="Unit value", verbose_name="Unit value")),
                ("quantity", models.PositiveIntegerField(default=0, help_text="Quantity", verbose_name="Quantity")),
                (
                    "initial_value",
                    models.FloatField(default=0, help_text="Initial value", verbose_name="Initial value"),
                ),
                (
                    "budget_addition",
                    models.FloatField(default=0, help_text="Budget addition", verbose_name="Budget addition"),
                ),
                (
                    "budget_decrease",
                    models.FloatField(default=0, help_text="Budget decrease", verbose_name="Budget decrease"),
                ),
                (
                    "budget_description",
                    models.ForeignKey(
                        help_text="Budget description",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_description_budgets",
                        to="budget.budgetdescription",
                        verbose_name="Budget description",
                    ),
                ),
                (
                    "cost_centers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Cost centers",
                        related_name="cost_centers_budgets",
                        to="cost_center.costcenter",
                        verbose_name="Cost centers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
            },
        ),
    ]
