# Generated by Django 4.2.5 on 2023-09-27 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0003_project_area_project_is_it_taxable_and_more"),
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetDescription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(help_text="Code", max_length=150, unique=True, verbose_name="Code")),
                ("description", models.TextField(help_text="Description", verbose_name="Description")),
            ],
            options={
                "verbose_name": "Budget Description",
                "verbose_name_plural": "Budget Descriptions",
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Unit value", max_digits=22, verbose_name="Unit value"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0, help_text="Quantity", verbose_name="Quantity")),
                (
                    "initial_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Initial value",
                        max_digits=22,
                        verbose_name="Initial value",
                    ),
                ),
                (
                    "budget_addition",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Budget addition",
                        max_digits=22,
                        verbose_name="Budget addition",
                    ),
                ),
                (
                    "budget_decrease",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Budget decrease",
                        max_digits=22,
                        verbose_name="Budget decrease",
                    ),
                ),
                (
                    "budget_description",
                    models.ForeignKey(
                        help_text="Budget description",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_description_budgets",
                        to="budget.budgetdescription",
                        verbose_name="Budget description",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        help_text="Cost center",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_center_budgets",
                        to="integration.costcenter",
                        verbose_name="Cost center",
                    ),
                ),
                (
                    "expense_type",
                    models.ForeignKey(
                        help_text="Expense type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_type_budgets",
                        to="integration.expensetype",
                        verbose_name="Expense type",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_budgets",
                        to="project.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
            },
        ),
    ]
