# Generated by Django 4.2.7 on 2023-11-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="project",
            field=models.ForeignKey(
                help_text="Project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_budgets",
                to="project.project",
                verbose_name="Project",
            ),
        ),
    ]
