# Generated by Django 4.2.5 on 2023-10-04 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expense_type", "0001_initial"),
        ("cost_center", "0002_remove_costcenter_cost_category"),
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="cost_center",
            field=models.ForeignKey(
                help_text="Cost center",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_center_budgets",
                to="cost_center.costcenter",
                verbose_name="Cost center",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="expense_type",
            field=models.ForeignKey(
                help_text="Expense type",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_type_budgets",
                to="expense_type.expensetype",
                verbose_name="Expense type",
            ),
        ),
    ]
