# Generated by Django 4.2.7 on 2023-11-26 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_alter_project_budget"),
        ("budget", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisionCart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "total_provisioned_amount",
                    models.FloatField(
                        default=0, help_text="Total provisioned amount", verbose_name="Total provisioned amount"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_provision_carts",
                        to="project.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_provision_carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provision Cart",
                "verbose_name_plural": "Provision Carts",
            },
        ),
        migrations.CreateModel(
            name="ProvisionCartBudget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "provosioned_amount",
                    models.FloatField(default=0, help_text="Provosioned amount", verbose_name="Provosioned amount"),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_provision_budgets",
                        to="budget.budget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "provision_cart",
                    models.ForeignKey(
                        help_text="Provision Cart",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provision_cart_provision_budgets",
                        to="budget.provisioncart",
                        verbose_name="Provision Cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provision Budget",
                "verbose_name_plural": "Provision Budgets",
            },
        ),
    ]
