# Generated by Django 4.2.5 on 2023-10-07 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expense_type", "0001_initial"),
        ("budget", "0002_alter_budget_cost_center_alter_budget_expense_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="expense_type",
        ),
        migrations.RemoveField(
            model_name="budgetdescription",
            name="code",
        ),
        migrations.AddField(
            model_name="budgetdescription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 10, 7, 15, 53, 49, 356434, tzinfo=datetime.timezone.utc),
                help_text="Date time on which the object was created.",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetdescription",
            name="expense_type",
            field=models.ForeignKey(
                default="",
                help_text="Expense type",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_type_budgets",
                to="expense_type.expensetype",
                verbose_name="Expense type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetdescription",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Designates whether this record is active or not.", verbose_name="status"
            ),
        ),
        migrations.AddField(
            model_name="budgetdescription",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date time on which the object was last updated.", verbose_name="updated at"
            ),
        ),
    ]
