# Generated by Django 4.2.6 on 2023-10-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expense_concept", "0002_alter_expenseconcept_code"),
        ("budget", "0003_remove_budget_expense_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetdescription",
            name="expense_type",
        ),
        migrations.AddField(
            model_name="budgetdescription",
            name="expense_concept",
            field=models.ForeignKey(
                default=1,
                help_text="Expense concept",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_concepts_budgets",
                to="expense_concept.expenseconcept",
                verbose_name="Expense concept",
            ),
            preserve_default=False,
        ),
    ]
