# Generated by Django 4.2.7 on 2023-11-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_project_budget"),
        ("budget", "0003_provisioncart_provisioncartbudget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provisioncart",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_provision_carts",
                to="project.project",
                verbose_name="Project",
            ),
        ),
    ]
