# Generated by Django 4.2.6 on 2023-11-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_remove_budgetdescription_expense_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="budget_addition",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Budget addition", max_digits=12, verbose_name="Budget addition"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="budget_decrease",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Budget decrease", max_digits=12, verbose_name="Budget decrease"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="initial_value",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Initial value", max_digits=12, verbose_name="Initial value"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="unit_value",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Unit value", max_digits=12, verbose_name="Unit value"
            ),
        ),
    ]
