# Generated by Django 4.2.7 on 2023-11-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_alter_provisioncart_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioncart",
            name="total_missing_amount",
            field=models.FloatField(
                default=0, help_text="Total provisioned amount", verbose_name="Total provisioned amount"
            ),
        ),
        migrations.AddField(
            model_name="provisioncart",
            name="total_required_amount",
            field=models.FloatField(
                default=0, help_text="Total provisioned amount", verbose_name="Total provisioned amount"
            ),
        ),
    ]
