# Generated by Django 4.2.7 on 2023-11-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business_unit", "0004_alter_businessunit_code"),
        ("budget", "0005_alter_budget_budget_addition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetCap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("cap", models.FloatField(default=0, help_text="Cap", verbose_name="Cap")),
                ("description", models.TextField(help_text="Description", verbose_name="Description")),
                (
                    "business_unit",
                    models.ForeignKey(
                        help_text="Business unit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_unit_budget_caps",
                        to="business_unit.businessunit",
                        verbose_name="Business unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Cap",
                "verbose_name_plural": "Budget Caps",
            },
        ),
    ]
