# Generated by Django 4.2.7 on 2023-11-26 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0006_alter_provisioncart_total_missing_amount_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="provisioncartbudget",
            unique_together={("provision_cart", "budget")},
        ),
    ]
