# Generated by Django 4.2.7 on 2023-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cost_center", "0006_remove_costcenter_area"),
        ("budget", "0006_budgetcap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="cost_center",
        ),
        migrations.AddField(
            model_name="budget",
            name="cost_centers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cost centers",
                related_name="cost_centers_budgets",
                to="cost_center.costcenter",
                verbose_name="Cost centers",
            ),
        ),
    ]
