# Generated by Django 4.2.7 on 2023-11-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0007_alter_provisioncartbudget_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioncart",
            name="finished",
            field=models.BooleanField(default=False, help_text="Finished", verbose_name="Finished"),
        ),
    ]
