# Generated by Django 5.0 on 2023-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0008_provisioncart_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioncartbudget",
            name="budget_taked",
            field=models.FloatField(default=0, help_text="Budget taked", verbose_name="Budget taked"),
        ),
    ]
