# Generated by Django 5.0 on 2023-12-10 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0009_provisioncartbudget_budget_taked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="provisioncartbudget",
            old_name="budget_taked",
            new_name="available_budget",
        ),
    ]
