# Generated by Django 5.0 on 2023-12-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0010_rename_budget_taked_provisioncartbudget_available_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provisioncart",
            name="total_missing_amount",
            field=models.FloatField(
                blank=True, default=0, help_text="Total missing amount", null=True, verbose_name="Total missing amount"
            ),
        ),
        migrations.AlterField(
            model_name="provisioncart",
            name="total_required_amount",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Total required amount",
                null=True,
                verbose_name="Total required amount",
            ),
        ),
    ]
