# Generated by Django 5.0 on 2023-12-13 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0011_alter_provisioncart_total_missing_amount_and_more"),
        ("project", "0003_alter_project_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudetTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("old_amount", models.FloatField(default=0, help_text="Old amount", verbose_name="Old amount")),
                ("new_amount", models.FloatField(default=0, help_text="New amount", verbose_name="New amount")),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Budget",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="budget_transactions",
                        to="budget.budget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_transactions",
                        to="project.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budet Transaction",
                "verbose_name_plural": "Budet Transactions",
            },
        ),
    ]
