# Generated by Django 5.0 on 2023-12-13 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0013_budettransaction_created_at_budettransaction_status_and_more"),
        ("project", "0003_alter_project_budget"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BudetTransaction",
            new_name="BudgetDecreaseTransaction",
        ),
        migrations.AlterModelOptions(
            name="budgetdecreasetransaction",
            options={
                "verbose_name": "Budget Decrease Transaction",
                "verbose_name_plural": "Budget Decrease Transactions",
            },
        ),
    ]
