# Generated by Django 5.0 on 2023-12-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0015_provisioncart_observation"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioncart",
            name="requires_approval",
            field=models.BooleanField(default=False, help_text="Requires approval", verbose_name="Requires approval"),
        ),
    ]
