# Generated by Django 5.0 on 2023-12-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0016_provisioncart_requires_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioncart",
            name="approved",
            field=models.BooleanField(default=False, help_text="Approved", verbose_name="Approved"),
        ),
    ]
