# Generated by Django 5.0 on 2023-12-14 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0018_alter_provisioncart_approved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisionCartApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("approved", models.BooleanField(default=False, help_text="Approved?", verbose_name="Approved?")),
                (
                    "must_be_approved_by",
                    models.ForeignKey(
                        help_text="Must be approbed by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="must_be_approved_by_fk",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Must be approbed by",
                    ),
                ),
                (
                    "provision_cart",
                    models.ForeignKey(
                        help_text="Provision Cart",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provision_cart_provision_approval",
                        to="budget.provisioncart",
                        verbose_name="Provision Cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provision Cart Approval",
                "verbose_name_plural": "Provision Cart Approvals",
            },
        ),
    ]
