# Generated by Django 5.0 on 2023-12-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0019_provisioncartapproval"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioncartapproval",
            name="observation",
            field=models.TextField(default="", help_text="Observation", verbose_name="Observation"),
        ),
    ]
