# Generated by Django 5.0 on 2023-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0021_budgetdecreasetransaction_provision_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetdecreasetransaction",
            name="requiered_amount",
            field=models.FloatField(default=0, help_text="Requiered amount", verbose_name="Requiered amount"),
        ),
    ]
