# Generated by Django 5.0 on 2023-12-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0023_budget_budget_decrease_control"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="budget_decrease_control",
            field=models.FloatField(
                default=0, help_text="Budget decrease control", verbose_name="Budget decrease control"
            ),
        ),
    ]
