# Generated by Django 4.2.7 on 2023-12-24 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0024_alter_budget_budget_decrease_control"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetRedistributionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Budget Redistribution Item",
                "verbose_name_plural": "Budget Redistribution Items",
            },
        ),
        migrations.CreateModel(
            name="BudgetRedistribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "original_amount",
                    models.FloatField(
                        blank=True, default=0, help_text="Original amount", null=True, verbose_name="Original amount"
                    ),
                ),
                (
                    "redistributed_amount",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="Redistributed amount",
                        null=True,
                        verbose_name="Redistributed amount",
                    ),
                ),
                (
                    "new_amount",
                    models.FloatField(
                        blank=True, default=0, help_text="New amount", null=True, verbose_name="New amount"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, help_text="Observation", null=True, verbose_name="Observation"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, help_text="Requires approval", verbose_name="Requires approval"
                    ),
                ),
                ("approved", models.BooleanField(default=False, help_text="Approved", verbose_name="Approved")),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_budget_redistributions",
                        to="budget.budget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "must_be_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Must be approved by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_budget_redistributions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Must be approved by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Redistribution",
                "verbose_name_plural": "Budget Redistributions",
            },
        ),
    ]
