# Generated by Django 4.2.7 on 2023-12-24 15:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0025_budgetredistributionitem_budgetredistribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetredistribution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 12, 24, 15, 47, 28, 283101, tzinfo=datetime.timezone.utc),
                help_text="Date time on which the object was created.",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetredistribution",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Designates whether this record is active or not.", verbose_name="status"
            ),
        ),
        migrations.AddField(
            model_name="budgetredistribution",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date time on which the object was last updated.", verbose_name="updated at"
            ),
        ),
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="budget",
            field=models.ForeignKey(
                default="",
                help_text="Budget",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="budget_budget_redistribution_items",
                to="budget.budget",
                verbose_name="Budget",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="budget_redistribution",
            field=models.ForeignKey(
                default="",
                help_text="Budget Redistribution",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="budget_redistribution_budget_redistribution_items",
                to="budget.budgetredistribution",
                verbose_name="Budget Redistribution",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 12, 24, 15, 48, 0, 871891, tzinfo=datetime.timezone.utc),
                help_text="Date time on which the object was created.",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="new_amount",
            field=models.FloatField(
                blank=True, default=0, help_text="New amount", null=True, verbose_name="New amount"
            ),
        ),
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="original_amount",
            field=models.FloatField(
                blank=True, default=0, help_text="Original amount", null=True, verbose_name="Original amount"
            ),
        ),
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="redistributed_amount",
            field=models.FloatField(
                blank=True, default=0, help_text="Redistributed amount", null=True, verbose_name="Redistributed amount"
            ),
        ),
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Designates whether this record is active or not.", verbose_name="status"
            ),
        ),
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date time on which the object was last updated.", verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="budgetredistribution",
            name="must_be_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Must be approved by",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_budget_redistributions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Must be approved by",
            ),
        ),
    ]
