# Generated by Django 4.2.7 on 2023-12-24 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0026_budgetredistribution_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetredistribution",
            name="finished",
            field=models.BooleanField(default=False, help_text="Finished", verbose_name="Finished"),
        ),
        migrations.AddField(
            model_name="budgetredistribution",
            name="user",
            field=models.ForeignKey(
                default="",
                help_text="User",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
            preserve_default=False,
        ),
    ]
