# Generated by Django 4.2.7 on 2023-12-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0027_budgetredistribution_finished_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetredistribution",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                help_text="Budget",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_budget_redistributions",
                to="budget.budget",
                verbose_name="Budget",
            ),
        ),
    ]
