# Generated by Django 4.2.7 on 2023-12-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0028_alter_budgetredistribution_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="processed",
            field=models.BooleanField(default=False, help_text="Processed", verbose_name="Processed"),
        ),
    ]
