# Generated by Django 4.2.7 on 2023-12-24 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0029_budgetredistributionitem_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetredistributionitem",
            name="budget_redistribution",
            field=models.ForeignKey(
                help_text="Budget Redistribution",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_redistribution_budget_redistribution_items",
                to="budget.budgetredistribution",
                verbose_name="Budget Redistribution",
            ),
        ),
    ]
