# Generated by Django 4.2.7 on 2023-12-24 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0030_alter_budgetredistributionitem_budget_redistribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="approved",
            field=models.BooleanField(default=False, help_text="Approved", verbose_name="Approved"),
        ),
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="must_be_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Must be approved by",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_budget_redistribution_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Must be approved by",
            ),
        ),
        migrations.AddField(
            model_name="budgetredistributionitem",
            name="requires_approval",
            field=models.BooleanField(default=False, help_text="Requires approval", verbose_name="Requires approval"),
        ),
    ]
