# Generated by Django 4.2.7 on 2023-12-25 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0031_budgetredistributionitem_approved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetRedistributionTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "original_amount",
                    models.FloatField(default=0, help_text="Original amount", verbose_name="Original amount"),
                ),
                (
                    "redistributed_amount",
                    models.FloatField(
                        default=0, help_text="Redistributed amount", verbose_name="Redistributed amount"
                    ),
                ),
                ("new_amount", models.FloatField(default=0, help_text="New amount", verbose_name="New amount")),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Budget",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="budget.budget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "redistribution_item",
                    models.ForeignKey(
                        help_text="Redistribution item",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="redistribution_item_budget_redistribution_transactions",
                        to="budget.budgetredistributionitem",
                        verbose_name="Redistribution item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Redistribution Transaction",
                "verbose_name_plural": "Budget Redistribution Transactions",
            },
        ),
    ]
