# Generated by Django 4.2.7 on 2023-12-25 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0032_budgetredistributiontransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetRedistributionItemApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approved", models.BooleanField(default=False, help_text="Approved", verbose_name="Approved")),
                (
                    "budget_redistribution_item",
                    models.ForeignKey(
                        help_text="Budget Redistribution Item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_redistribution_item_budget_redistribution_item_approvals",
                        to="budget.budgetredistributionitem",
                        verbose_name="Budget Redistribution Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Redistribution Item Approval",
                "verbose_name_plural": "Budget Redistribution Item Approvals",
            },
        ),
    ]
