# Generated by Django 4.2.7 on 2023-12-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0034_budgetredistributionitemapproval_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioncart",
            name="rejected",
            field=models.BooleanField(default=False, help_text="Rejected", verbose_name="Rejected"),
        ),
        migrations.AddField(
            model_name="provisioncartapproval",
            name="rejected",
            field=models.BooleanField(default=False, help_text="Rejected", verbose_name="Rejected"),
        ),
    ]
