# Generated by Django 4.2.7 on 2024-01-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0035_provisioncart_rejected_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetAddition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("finished", models.BooleanField(default=False, help_text="Finished", verbose_name="Finished")),
                (
                    "observation",
                    models.TextField(blank=True, help_text="Observation", null=True, verbose_name="Observation"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, help_text="Requires approval", verbose_name="Requires approval"
                    ),
                ),
                ("approved", models.BooleanField(default=False, help_text="Approved", verbose_name="Approved")),
                (
                    "must_be_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Must be approved by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Must be approved by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Addition",
                "verbose_name_plural": "Budget Additions",
            },
        ),
        migrations.CreateModel(
            name="BudgetAdditionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "original_amount",
                    models.FloatField(
                        blank=True, default=0, help_text="Original amount", null=True, verbose_name="Original amount"
                    ),
                ),
                (
                    "added_amount",
                    models.FloatField(
                        blank=True, default=0, help_text="Added amount", null=True, verbose_name="Added amount"
                    ),
                ),
                (
                    "new_amount",
                    models.FloatField(
                        blank=True, default=0, help_text="New amount", null=True, verbose_name="New amount"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, help_text="Requires approval", verbose_name="Requires approval"
                    ),
                ),
                ("approved", models.BooleanField(default=False, help_text="Approved", verbose_name="Approved")),
                ("processed", models.BooleanField(default=False, help_text="Processed", verbose_name="Processed")),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Budget",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="budget.budget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "budget_addition",
                    models.ForeignKey(
                        help_text="Budget addition item",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="budget.budgetaddition",
                        verbose_name="Budget addition item",
                    ),
                ),
                (
                    "must_be_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Must be approved by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Must be approved by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Addition Item",
                "verbose_name_plural": "Budget Addition Items",
            },
        ),
    ]
