# Generated by Django 4.2.7 on 2024-01-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0036_budgetaddition_budgetadditionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetadditionitem",
            name="rejected",
            field=models.BooleanField(default=False, help_text="Rejected", verbose_name="Rejected"),
        ),
    ]
