# Generated by Django 4.2.7 on 2024-01-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0037_budgetadditionitem_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetaddition",
            name="rejected",
            field=models.BooleanField(default=False, help_text="Rejected", verbose_name="Rejected"),
        ),
    ]
