# Generated by Django 4.2.7 on 2024-01-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0039_budgetredistribution_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetredistributionitemapproval",
            name="observation",
            field=models.TextField(
                blank=True, default="", help_text="Observation", null=True, verbose_name="Observation"
            ),
        ),
    ]
