# Generated by Django 4.2.7 on 2024-01-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0040_budgetredistributionitemapproval_observation"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetredistribution",
            name="approval_observation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Approval observation",
                null=True,
                verbose_name="Approval observation",
            ),
        ),
    ]
