# Generated by Django 4.2.7 on 2024-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0041_budgetredistribution_approval_observation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetaddition",
            name="requires_approval",
            field=models.BooleanField(default=True, help_text="Requires approval", verbose_name="Requires approval"),
        ),
        migrations.AlterField(
            model_name="budgetadditionitem",
            name="requires_approval",
            field=models.BooleanField(default=True, help_text="Requires approval", verbose_name="Requires approval"),
        ),
    ]
