# Generated by Django 4.2.7 on 2024-01-10 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0042_alter_budgetaddition_requires_approval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetaddition",
            name="approval_observation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Approval Observation",
                null=True,
                verbose_name="Approval Observation",
            ),
        ),
        migrations.AlterField(
            model_name="budgetaddition",
            name="observation",
            field=models.TextField(
                blank=True, default="", help_text="Observation", null=True, verbose_name="Observation"
            ),
        ),
        migrations.CreateModel(
            name="BudgetAdditionApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("approved", models.BooleanField(default=False, help_text="Approved?", verbose_name="Approved?")),
                ("rejected", models.BooleanField(default=False, help_text="Rejected", verbose_name="Rejected")),
                (
                    "budget_addition",
                    models.ForeignKey(
                        help_text="Budget Addition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_addition_approval",
                        to="budget.budgetaddition",
                        verbose_name="Budget Addition",
                    ),
                ),
                (
                    "must_be_approved_by",
                    models.ForeignKey(
                        help_text="Must be approbed by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_addition_must_be_approved_by_fk",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Must be approbed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provision Cart Approval",
                "verbose_name_plural": "Provision Cart Approvals",
            },
        ),
    ]
