# Generated by Django 4.2.7 on 2024-01-12 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0004_contract_cost_center_contract_third"),
        ("purchase_order", "0003_alter_purchaseorder_fecentrega"),
        ("integration", "0004_purchaseorder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0044_budgetaddtiontransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commitment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "contract_or_po",
                    models.CharField(
                        choices=[("CT", "Contract"), ("PO", "Purchase order")],
                        default="CT",
                        help_text="Contract or PO",
                        max_length=2,
                        verbose_name="Contract or PO",
                    ),
                ),
                ("has_tax", models.BooleanField(default=False, help_text="Has tax", verbose_name="Has tax")),
                (
                    "provisio_budget_amount",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="Provision budget amount",
                        null=True,
                        verbose_name="Provision budget amount",
                    ),
                ),
                (
                    "required_amount",
                    models.FloatField(
                        blank=True, default=0, help_text="Required amount", null=True, verbose_name="Required amount"
                    ),
                ),
                (
                    "diference_between_required_and_provisioned",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="Difference between required and provisioned",
                        null=True,
                        verbose_name="Difference between required and provisioned",
                    ),
                ),
                ("finished", models.BooleanField(default=False, help_text="Finished", verbose_name="Finished")),
                (
                    "observation",
                    models.TextField(blank=True, help_text="Observation", null=True, verbose_name="Observation"),
                ),
                (
                    "approval_observation",
                    models.TextField(
                        blank=True, help_text="Approval Observation", null=True, verbose_name="Approval Observation"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, help_text="Requires approval", verbose_name="Requires approval"
                    ),
                ),
                ("approved", models.BooleanField(default=True, help_text="Approved", verbose_name="Approved")),
                ("rejected", models.BooleanField(default=False, help_text="Rejected", verbose_name="Rejected")),
                (
                    "provision_cart",
                    models.ForeignKey(
                        blank=True,
                        help_text="Provision Cart",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="provision_cart_commitments",
                        to="budget.provisioncart",
                        verbose_name="Provision Cart",
                    ),
                ),
                (
                    "third",
                    models.ForeignKey(
                        blank=True,
                        help_text="Third",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="third_commitments",
                        to="integration.third",
                        verbose_name="Third",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_commintments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commitment",
                "verbose_name_plural": "Commitments",
            },
        ),
        migrations.CreateModel(
            name="CommitmentPO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        help_text="Commitment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitment_po",
                        to="budget.commitment",
                        verbose_name="Commitment",
                    ),
                ),
                (
                    "cont",
                    models.ForeignKey(
                        help_text="Purchase Order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_order_commitment_po",
                        to="purchase_order.purchaseorder",
                        verbose_name="Purchase Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commitment PO",
                "verbose_name_plural": "Commitment POs",
            },
        ),
        migrations.CreateModel(
            name="CommitmentContract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        help_text="Commitment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitment_contract",
                        to="budget.commitment",
                        verbose_name="Commitment",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_commitment_po",
                        to="contract.contract",
                        verbose_name="Contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commitment Contract",
                "verbose_name_plural": "Commitment Contracts",
            },
        ),
    ]
