# Generated by Django 4.2.7 on 2024-01-12 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0045_commitment_commitmentpo_commitmentcontract"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commitment",
            old_name="provisio_budget_amount",
            new_name="provision_budget_amount",
        ),
    ]
