# Generated by Django 4.2.7 on 2024-01-12 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0046_rename_provisio_budget_amount_commitment_provision_budget_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commitmentpo",
            old_name="cont",
            new_name="po",
        ),
    ]
