# Generated by Django 4.2.7 on 2024-01-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0047_rename_cont_commitmentpo_po"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commitment",
            name="contract_or_po",
            field=models.CharField(
                blank=True,
                choices=[("CT", "Contract"), ("PO", "Purchase order")],
                help_text="Contract or PO",
                max_length=2,
                null=True,
                verbose_name="Contract or PO",
            ),
        ),
    ]
