# Generated by Django 4.2.7 on 2024-01-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0049_commitmentrelease_commitmentrealeaseitems"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commitmentrealeaseitems",
            options={"verbose_name": "Commitment Realease Item", "verbose_name_plural": "Commitment Realease Items"},
        ),
        migrations.AddField(
            model_name="commitmentrelease",
            name="total_to_released",
            field=models.FloatField(
                blank=True, default=0, help_text="Total to released", null=True, verbose_name="Total to released"
            ),
        ),
    ]
