# Generated by Django 4.2.7 on 2024-01-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0050_alter_commitmentrealeaseitems_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commitmentrelease",
            name="total_to_released",
        ),
        migrations.AddField(
            model_name="commitmentrelease",
            name="total_released",
            field=models.FloatField(
                blank=True, default=0, help_text="Total released", null=True, verbose_name="Total released"
            ),
        ),
    ]
