# Generated by Django 4.2.7 on 2024-01-18 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0054_alter_commitment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commitment",
            name="contract_or_po",
            field=models.CharField(
                blank=True,
                choices=[("CT", "Contract"), ("PO", "Purchase order"), ("CO", "Consumption"), ("LG", "Legalization")],
                help_text="Contract or PO",
                max_length=2,
                null=True,
                verbose_name="Contract or PO",
            ),
        ),
        migrations.CreateModel(
            name="CommitmentNotRelated",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("key", models.CharField(blank=True, help_text="Key", max_length=100, null=True, verbose_name="Key")),
                (
                    "commitment",
                    models.ForeignKey(
                        help_text="Commitment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitment_not_related",
                        to="budget.commitment",
                        verbose_name="Commitment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commitment No related",
                "verbose_name_plural": "Commitment Not related",
            },
        ),
    ]
