# Generated by Django 4.2.7 on 2024-01-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0055_alter_commitment_contract_or_po_commitmentnotrelated"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitmentnotrelated",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("CT", "Contract"), ("PO", "Purchase order"), ("CO", "Consumption"), ("LG", "Legalization")],
                help_text="Contract or PO",
                max_length=2,
                null=True,
                verbose_name="Contract or PO",
            ),
        ),
    ]
