# Generated by Django 4.2.7 on 2024-01-18 03:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0059_alter_commitmentnotrelated_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commitment",
            name="approval_observation",
        ),
        migrations.RemoveField(
            model_name="commitment",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="commitment",
            name="observation",
        ),
        migrations.RemoveField(
            model_name="commitment",
            name="rejected",
        ),
        migrations.RemoveField(
            model_name="commitment",
            name="requires_approval",
        ),
    ]
