# Generated by Django 4.2.7 on 2024-02-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0061_commitmentrealeaseitems_budget_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="released_amount",
            field=models.FloatField(default=0, help_text="Released amount", verbose_name="Released amount"),
        ),
    ]
