# Generated by Django 4.2.7 on 2024-02-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0062_budget_released_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitmentOrphanRelease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "total_to_release",
                    models.FloatField(
                        blank=True, default=0, help_text="Total to release", null=True, verbose_name="Total to release"
                    ),
                ),
                (
                    "total_released",
                    models.FloatField(
                        blank=True, default=0, help_text="Total released", null=True, verbose_name="Total released"
                    ),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        help_text="Commitment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitment_orphan_release",
                        to="budget.commitment",
                        verbose_name="Commitment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commitment Release",
                "verbose_name_plural": "Commitment Releases",
            },
        ),
        migrations.CreateModel(
            name="CommitmentOrphanRealeaseItems",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "budget_amount",
                    models.FloatField(
                        blank=True, default=0, help_text="Budget amount", null=True, verbose_name="Budget amount"
                    ),
                ),
                (
                    "total_to_release",
                    models.FloatField(
                        blank=True, default=0, help_text="Total to release", null=True, verbose_name="Total to release"
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_commitment_orphan_release_items",
                        to="budget.budget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "commitment_release",
                    models.ForeignKey(
                        help_text="Commitment Release",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitment_orphan_release_items",
                        to="budget.commitmentorphanrelease",
                        verbose_name="Commitment Release",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commitment Realease Item",
                "verbose_name_plural": "Commitment Realease Items",
            },
        ),
    ]
