# Generated by Django 4.2.7 on 2024-02-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0064_commitmentorphanrelease_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commitmentorphanrealeaseitems",
            options={
                "verbose_name": "Commitment Realease Orphan Item",
                "verbose_name_plural": "Commitment Realease Orphan Items",
            },
        ),
        migrations.AlterModelOptions(
            name="commitmentorphanrelease",
            options={"verbose_name": "Commitment Orphan Release", "verbose_name_plural": "Commitment Orphan Releases"},
        ),
        migrations.AddField(
            model_name="commitmentorphanrelease",
            name="processed",
            field=models.BooleanField(default=False, help_text="Processed", verbose_name="Processed"),
        ),
    ]
