# Generated by Django 4.2.7 on 2024-02-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0065_alter_commitmentorphanrealeaseitems_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitmentorphanrealeaseitems",
            name="new_db_budget_amount",
            field=models.FloatField(
                blank=True, default=0, help_text="New budget amount", null=True, verbose_name="New budget amount"
            ),
        ),
    ]
