# Generated by Django 4.2.7 on 2024-02-04 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0066_commitmentorphanrealeaseitems_new_db_budget_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisionCartHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "total_required_amount",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="Total required amount",
                        null=True,
                        verbose_name="Total required amount",
                    ),
                ),
                (
                    "total_provisioned_amount",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="Total provisioned amount",
                        null=True,
                        verbose_name="Total provisioned amount",
                    ),
                ),
                (
                    "total_missing_amount",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="Total missing amount",
                        null=True,
                        verbose_name="Total missing amount",
                    ),
                ),
                ("finished", models.BooleanField(default=False, help_text="Finished", verbose_name="Finished")),
                (
                    "observation",
                    models.TextField(blank=True, help_text="Observation", null=True, verbose_name="Observation"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, help_text="Requires approval", verbose_name="Requires approval"
                    ),
                ),
                ("approved", models.BooleanField(default=True, help_text="Approved", verbose_name="Approved")),
                ("rejected", models.BooleanField(default=False, help_text="Rejected", verbose_name="Rejected")),
                (
                    "provision_cart",
                    models.ForeignKey(
                        help_text="Provision Cart",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provision_cart_history",
                        to="budget.provisioncart",
                        verbose_name="Provision Cart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_provision_history_carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provision Cart History",
                "verbose_name_plural": "Provision Cart Histories",
            },
        ),
        migrations.CreateModel(
            name="ProvisionCartBudgetHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "provosioned_amount",
                    models.FloatField(default=0, help_text="Provosioned amount", verbose_name="Provosioned amount"),
                ),
                (
                    "available_budget",
                    models.FloatField(default=0, help_text="Budget taked", verbose_name="Budget taked"),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_provision_history_budgets",
                        to="budget.budget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "provision_cart_history",
                    models.ForeignKey(
                        help_text="Provision Cart",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provision_cart_provision_budgets",
                        to="budget.provisioncarthistory",
                        verbose_name="Provision Cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provision Budget history",
                "verbose_name_plural": "Provision Budget histories",
                "unique_together": {("provision_cart_history", "budget")},
            },
        ),
    ]
