# Generated by Django 4.2.7 on 2024-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0068_alter_provisioncartbudgethistory_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioncart",
            name="total_released_amount",
            field=models.FloatField(
                default=0, help_text="Total released amount", null=True, verbose_name="Total released amount"
            ),
        ),
        migrations.AddField(
            model_name="provisioncartbudget",
            name="released_amount",
            field=models.FloatField(default=0, help_text="Released amount", verbose_name="Released amount"),
        ),
    ]
