# Generated by Django 4.2.7 on 2024-02-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0069_provisioncart_total_released_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitment",
            name="total_released",
            field=models.FloatField(
                blank=True, default=0, help_text="Total released", null=True, verbose_name="Total released"
            ),
        ),
    ]
