# Generated by Django 4.2.7 on 2024-02-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0071_provisioncartbudget_alreaday_taked_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provisioncartbudget",
            name="alreaday_taked_amount",
        ),
    ]
