# Generated by Django 4.2.7 on 2024-03-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0073_provisioncartbudgethistory_already_taked_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioncartapproval",
            name="apprived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Approved by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_by_fk",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
    ]
