# Generated by Django 4.2.7 on 2024-03-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0076_provisioncartanullationreason_provisioncart_annulled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="anulled_amount",
            field=models.FloatField(default=0, help_text="Anulled amount", verbose_name="Anulled amount"),
        ),
    ]
