# Generated by Django 4.2.7 on 2024-03-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0077_budget_anulled_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="provisioncartbudget",
            options={"verbose_name": "Provision Cart Budget", "verbose_name_plural": "Provision Cart Budgets"},
        ),
    ]
