# Generated by Django 4.2.7 on 2024-04-02 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0079_alter_provisioncartbudgethistory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetaddition",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Approved by",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
    ]
