# Generated by Django 4.2.7 on 2024-04-02 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0080_budgetaddition_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetaddition",
            name="rejected_by",
            field=models.ForeignKey(
                help_text="Rejected by",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rejected by",
            ),
        ),
    ]
