version: "3"

volumes:
  sicop_local_postgres_data: {}
  sicop_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sicop_local_django
    container_name: sicop_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.mssql
    ports:
      - "8080:8080"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sicop_production_postgres
    container_name: sicop_local_postgres
    volumes:
      - sicop_local_postgres_data:/var/lib/postgresql/data
      - sicop_local_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: sicop_local_docs
    container_name: sicop_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mssql
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./sicop:/app/sicop:z
      - ./manage.py:/app/manage.py:z
    ports:
      - "9090:9090"
    command: /start-docs

  redis:
    image: redis:6
    container_name: sicop_local_redis
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    image: sicop_local_celeryworker
    container_name: sicop_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports:
      - "5554:5554"
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sicop_local_celerybeat
    container_name: sicop_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports:
      - "5553:5553"
    command: /start-celerybeat

  flower:
    <<: *django
    image: sicop_local_flower
    container_name: sicop_local_flower
    ports:
      - "5556:5556"
    command: /start-flower
