version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: sicop_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
      - ./.envs/.local/.mssql
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sicop_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: sicop_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:90:90"
<<<<<<< HEAD
      - "0.0.0.0:443:8443"
=======
      - "0.0.0.0:443:443"
>>>>>>> 8cfdd2e0134cc35c1d339424357d06dc48dfdfca
      - "0.0.0.0:5562:5562"

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: sicop_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sicop_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: sicop_production_flower
    command: /start-flower
