# Generated by Django 4.2.7 on 2023-11-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Area name", max_length=150, unique=True, verbose_name="Area name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Area description", null=True, verbose_name="Area description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
            },
        ),
        migrations.CreateModel(
            name="AreaRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Area Role code", max_length=150, unique=True, verbose_name="Area Role code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Area Role name", max_length=150, unique=True, verbose_name="Area Role name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Area Role",
                "verbose_name_plural": "Area Roles",
            },
        ),
        migrations.CreateModel(
            name="AreaMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        help_text="Area",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="area.area",
                        verbose_name="Area",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Area Role",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="area.arearole",
                        verbose_name="Area Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area Member",
                "verbose_name_plural": "Area Members",
            },
        ),
    ]
