# Generated by Django 4.2.5 on 2023-09-25 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("area", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaMembers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "area",
                    models.ForeignKey(
                        help_text="Area",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="area.area",
                        verbose_name="Area",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area Members",
                "verbose_name_plural": "Area Memberss",
            },
        ),
    ]
