# Generated by Django 5.0 on 2023-12-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("area", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="areamember",
            name="job_title",
            field=models.CharField(
                blank=True, default="", help_text="Job Title", max_length=150, null=True, verbose_name="Job Title"
            ),
        ),
    ]
