# Generated by Django 4.2.5 on 2023-09-25 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("area", "0003_areamembers_created_at_areamembers_status_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AreaMembers",
            new_name="AreaMember",
        ),
        migrations.AlterModelOptions(
            name="areamember",
            options={"verbose_name": "Area Member", "verbose_name_plural": "Area Members"},
        ),
    ]
