# Generated by Django 4.2.7 on 2023-11-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("area", "0004_rename_areamembers_areamember_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        help_text="Area Role code", max_length=150, unique=True, verbose_name="Area Role code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Area Role name", max_length=150, unique=True, verbose_name="Area Role name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Area Role",
                "verbose_name_plural": "Area Roles",
            },
        ),
    ]
