# Generated by Django 4.2.7 on 2023-11-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("area", "0007_areamember_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areamember",
            name="role",
            field=models.ForeignKey(
                default="",
                help_text="Area Role",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="area.arearole",
                verbose_name="Area Role",
            ),
            preserve_default=False,
        ),
    ]
