# Generated by Django 4.2.7 on 2024-03-20 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("area", "0003_areamember_job_title"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("menu", models.CharField(help_text="Menu", max_length=150, verbose_name="Menu")),
                ("icon", models.CharField(help_text="Icon", max_length=150, verbose_name="Icon")),
                ("slug", models.SlugField(help_text="Slug", max_length=150, unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
            },
        ),
        migrations.CreateModel(
            name="MenuOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(help_text="Name", max_length=150, verbose_name="Name")),
                (
                    "groups",
                    models.ManyToManyField(
                        help_text="Security groups",
                        related_name="menu_options",
                        to="auth.group",
                        verbose_name="Security groups",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        help_text="Menu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_options",
                        to="maloka_menu.menu",
                        verbose_name="Menu",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        help_text="Security roles",
                        related_name="menu_options",
                        to="area.arearole",
                        verbose_name="Security roles",
                    ),
                ),
                (
                    "special_roles",
                    models.ManyToManyField(
                        help_text="Special roles",
                        related_name="menu_special_options",
                        to="area.arearole",
                        verbose_name="Special roles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Option",
                "verbose_name_plural": "Menu Options",
            },
        ),
    ]
