# Generated by Django 4.2.7 on 2024-03-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maloka_menu", "0003_alter_menuoption_special_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuoption",
            name="url_name",
            field=models.CharField(default="#", help_text="URL name", max_length=250, verbose_name="URL name"),
        ),
    ]
