# Generated by Django 4.2.7 on 2024-03-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maloka_menu", "0004_menuoption_url_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name", max_length=150, verbose_name="Name")),
                (
                    "menus",
                    models.ManyToManyField(
                        help_text="Menus", related_name="menu_groups", to="maloka_menu.menu", verbose_name="Menus"
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Group",
                "verbose_name_plural": "Menu Groups",
            },
        ),
    ]
