# Generated by Django 4.2.7 on 2024-03-20 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maloka_menu", "0007_remove_menugroup_menus"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Menu Group",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_group",
                to="maloka_menu.menugroup",
                verbose_name="Menu Group",
            ),
        ),
    ]
