# Generated by Django 4.2.7 on 2024-03-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maloka_menu", "0009_menuoption_url_complement"),
    ]

    operations = [
        migrations.AddField(
            model_name="menugroup",
            name="order",
            field=models.IntegerField(blank=True, help_text="Order", null=True, unique=True, verbose_name="Order"),
        ),
    ]
