# Generated by Django 4.2.7 on 2024-04-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area", "0003_areamember_job_title"),
        ("maloka_menu", "0010_menugroup_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuoption",
            name="special_roles",
            field=models.ManyToManyField(
                help_text="Special roles",
                related_name="menu_special_options",
                to="area.arearole",
                verbose_name="Special roles",
            ),
        ),
    ]
