# Generated by Django 4.2.6 on 2023-10-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense_concept", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseconcept",
            name="code",
            field=models.SlugField(blank=True, help_text="Code", max_length=150, null=True, verbose_name="Code"),
        ),
    ]
