# Generated by Django 4.2.5 on 2023-09-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("expense_concept", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("code", models.SlugField(help_text="Code", max_length=150, unique=True, verbose_name="Code")),
                ("name", models.CharField(help_text="Name", max_length=150, verbose_name="Name")),
                (
                    "expense_concepts",
                    models.ManyToManyField(
                        help_text="Expense Concepts",
                        related_name="expense_concepts",
                        to="expense_concept.expenseconcept",
                        verbose_name="Expense Concepts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Type",
                "verbose_name_plural": "Expense Types",
            },
        ),
    ]
