apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: celeryflower
  namespace: local
  name: celeryflower # name should be anything put flower: https://github.com/mher/flower/issues/738
spec:
  replicas: 1
  selector:
    matchLabels:
      service: celeryflower
  template:
    metadata:
      labels:
        service: celeryflower
    spec:
      containers:
        - args:
            - /start-flower
          envFrom:
            - configMapRef:
                name: envs-local-django
            - configMapRef:
                name: envs-local-postgres
            - secretRef:
                name: secrets-local-django
            - secretRef:
                name: secrets-local-postgres
          image: jonathanurzolamaldonado/sicop_local_flower
          name: celeryflower
          ports:
            - containerPort: 5555
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  name: celeryflower
  namespace: local
  labels:
    service: celeryflower
spec:
  ports:
    - port: 5555
      targetPort: 5555
      name: http
  selector:
    service: celeryflower
