apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: postgres
  namespace: local
  name: postgres
spec:
  selector:
    matchLabels:
      service: postgres
  serviceName: "postgres"
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: envs-local-postgres
            - secretRef:
                name: secrets-local-postgres
          image: jonathanurzolamaldonado/sicop_production_postgres
          name: postgres
          ports:
            - containerPort: 5432
              name: postgredb
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
              subPath: postgres
            - mountPath: /backups
              name: postgres-backups
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: postgres-backups
          persistentVolumeClaim:
            claimName: postgres-backups
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgres
  namespace: local
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
  selector:
    service: postgres
status:
  loadBalancer: {}
