# Generated by Django 5.0 on 2023-12-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Job Title"),
        ),
    ]
