# Generated by Django 4.2.7 on 2023-12-25 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 12, 25, 2, 23, 22, 221745, tzinfo=datetime.timezone.utc),
                help_text="Date",
                verbose_name="Date",
            ),
            preserve_default=False,
        ),
    ]
