# Generated by Django 4.2.7 on 2024-01-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0002_certificate_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="code",
            field=models.CharField(default="", help_text="Code", max_length=255, verbose_name="Code"),
        ),
    ]
