from django.contrib.auth import views as auth_views
from django.urls import path

from sicop.users.views import (
    GroupCreateView,
    GroupDetailView,
    GroupListView,
    GroupUpdateView,
    LoginView,
    ResetPasswordMessageView,
    ResetPasswordView,
    SignupView,
    UserCreateView,
    UserListView,
    UserPasswordChangeView,
    UserProfileUpdateView,
    UserProfileView,
    UserUpdateView,
    UsetDetailView,
    logout_view,
)

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(),
        name="user_login",
    ),
    path(
        "logout/",
        logout_view,
        name="user_logout",
    ),
    path(
        "signup/",
        SignupView.as_view(),
        name="user_signup",
    ),
    path(
        "reset-password/",
        ResetPasswordView.as_view(),
        name="user_reset_password",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="sicop/users/reset/password_reset_confirm.html",
        ),
        name="user_password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="sicop/users/reset/password_reset_complete.html",
        ),
        name="user_password_reset_complete",
    ),
    path(
        "password-reset-done/",
        ResetPasswordMessageView.as_view(),
        name="user_password_reset_done",
    ),
    path(
        "profile/info/",
        UserProfileView.as_view(),
        name="user_profile",
    ),
    path(
        "profile/password/",
        UserPasswordChangeView.as_view(),
        name="user_password_change",
    ),
    path(
        "group/list",
        GroupListView.as_view(),
        name="user_group_list",
    ),
    path(
        "group/detail/<int:pk>",
        GroupDetailView.as_view(),
        name="user_group_detail",
    ),
    path(
        "group/update/<int:pk>",
        GroupUpdateView.as_view(),
        name="user_group_update",
    ),
    path(
        "group/create",
        GroupCreateView.as_view(),
        name="user_group_create",
    ),
    path(
        "user/list",
        UserListView.as_view(),
        name="user_list",
    ),
    path(
        "user/detail/<int:pk>",
        UsetDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "user/create",
        UserCreateView.as_view(),
        name="user_create",
    ),
    path(
        "user/update/<int:pk>",
        UserUpdateView.as_view(),
        name="user_update",
    ),
    path(
        "user/profile/update",
        UserProfileUpdateView.as_view(),
        name="user_profile_update",
    ),
]
