# Generated by Django 4.2.7 on 2023-11-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(help_text="Name", max_length=150, verbose_name="Name")),
                (
                    "commertial_name",
                    models.CharField(help_text="Commertial name", max_length=150, verbose_name="Commertial name"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, help_text="Phone", max_length=150, null=True, verbose_name="Phone"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="Address", max_length=250, null=True, verbose_name="Address"
                    ),
                ),
                ("dni", models.CharField(help_text="DNI", max_length=150, unique=True, verbose_name="DNI")),
            ],
            options={
                "verbose_name": "Contractor",
                "verbose_name_plural": "Contractors",
            },
        ),
        migrations.CreateModel(
            name="ContractorFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("file", models.FileField(help_text="File", upload_to="contractor_files", verbose_name="File")),
                (
                    "contractor",
                    models.ForeignKey(
                        help_text="Contractor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contractor.contractor",
                        verbose_name="Contractor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractor File",
                "verbose_name_plural": "Contractor Files",
            },
        ),
    ]
