# Generated by Django 4.2.5 on 2023-09-25 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 9, 25, 13, 30, 51, 270967, tzinfo=datetime.timezone.utc),
                help_text="Date time on which the object was created.",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractor",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Designates whether this record is active or not.", verbose_name="status"
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date time on which the object was last updated.", verbose_name="updated at"
            ),
        ),
        migrations.AddField(
            model_name="contractorfile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 9, 25, 13, 30, 58, 810641, tzinfo=datetime.timezone.utc),
                help_text="Date time on which the object was created.",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractorfile",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Designates whether this record is active or not.", verbose_name="status"
            ),
        ),
        migrations.AddField(
            model_name="contractorfile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date time on which the object was last updated.", verbose_name="updated at"
            ),
        ),
    ]
