# Generated by Django 4.2.6 on 2023-10-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractor", "0002_contractor_created_at_contractor_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contractor",
            old_name="last_name",
            new_name="commertial_name",
        ),
        migrations.RenameField(
            model_name="contractor",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="contractor_type",
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="email",
        ),
        migrations.AlterField(
            model_name="contractor",
            name="address",
            field=models.CharField(blank=True, help_text="Address", max_length=250, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="phone",
            field=models.CharField(blank=True, help_text="Phone", max_length=150, null=True, verbose_name="Phone"),
        ),
    ]
