# Generated by Django 4.2.6 on 2023-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractor", "0003_rename_last_name_contractor_commertial_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="commertial_name",
            field=models.CharField(help_text="Commertial name", max_length=150, verbose_name="Commertial name"),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="name",
            field=models.CharField(help_text="Name", max_length=150, verbose_name="Name"),
        ),
    ]
