apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: celerybeat
  namespace: local
  name: celerybeat
spec:
  replicas: 1
  selector:
    matchLabels:
      service: celerybeat
  template:
    metadata:
      labels:
        service: celerybeat
    spec:
      containers:
        - args:
            - /start-celerybeat
          envFrom:
            - configMapRef:
                name: envs-local-django
            - configMapRef:
                name: envs-local-postgres
            - secretRef:
                name: secrets-local-django
            - secretRef:
                name: secrets-local-postgres
          image: jonathanurzolamaldonado/sicop_local_celerybeat
          name: celerybeat
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /app/sicop/media
              name: media
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
