apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: redis
  namespace: local
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  strategy: {}
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - image: redis:6
          name: redis
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: local
  name: redis
  labels:
    service: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    service: redis
