# Generated by Django 4.2.7 on 2024-01-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "IdContrato",
                    models.CharField(
                        blank=True, help_text="Contract ID", max_length=250, null=True, verbose_name="Contract ID"
                    ),
                ),
                (
                    "TipContrato",
                    models.CharField(
                        blank=True, help_text="Contract Type", max_length=250, null=True, verbose_name="Contract Type"
                    ),
                ),
                (
                    "Cumplido",
                    models.CharField(
                        blank=True, help_text="Compliment", max_length=250, null=True, verbose_name="Compliment"
                    ),
                ),
                (
                    "Estado",
                    models.CharField(
                        blank=True,
                        help_text="Contract Status",
                        max_length=250,
                        null=True,
                        verbose_name="Contract Status",
                    ),
                ),
                (
                    "IdTercer",
                    models.CharField(
                        blank=True, help_text="Third ID", max_length=250, null=True, verbose_name="Third ID"
                    ),
                ),
                (
                    "IdCenCos",
                    models.CharField(
                        blank=True,
                        help_text="Cost Center ID",
                        max_length=250,
                        null=True,
                        verbose_name="Cost Center ID",
                    ),
                ),
                (
                    "FechaCon",
                    models.DateField(blank=True, help_text="Contract Date", null=True, verbose_name="Contract Date"),
                ),
                (
                    "FechaIni",
                    models.DateField(blank=True, help_text="Start Date", null=True, verbose_name="Start Date"),
                ),
                (
                    "FechaFin",
                    models.DateField(blank=True, help_text="Finish Date", null=True, verbose_name="Finish Date"),
                ),
                ("Objeto", models.TextField(blank=True, help_text="Object", null=True, verbose_name="Object")),
                (
                    "ValSinIVA",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="Value Without Tax",
                        null=True,
                        verbose_name="Value Without Tax",
                    ),
                ),
                (
                    "ValIVA",
                    models.FloatField(
                        blank=True, default=0, help_text="Tax Value", null=True, verbose_name="Tax Value"
                    ),
                ),
                (
                    "ValTot",
                    models.FloatField(
                        blank=True, default=0, help_text="Total Value", null=True, verbose_name="Total Value"
                    ),
                ),
                (
                    "NumCompro",
                    models.CharField(
                        blank=True,
                        help_text="Voucher Number",
                        max_length=250,
                        null=True,
                        verbose_name="Voucher Number",
                    ),
                ),
                (
                    "Operac",
                    models.CharField(
                        blank=True, help_text="Operation", max_length=250, null=True, verbose_name="Operation"
                    ),
                ),
                (
                    "FecMod",
                    models.DateField(blank=True, help_text="FecMod", null=True, verbose_name="Modification Date"),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
            },
        ),
    ]
