# Generated by Django 4.2.7 on 2024-01-11 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0003_contract_cumplido_contract_idcontrato_and_more"),
        ("cost_center", "0001_initial"),
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                help_text="Cost Center",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cost_center.costcenter",
                verbose_name="Cost Center",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="third",
            field=models.ForeignKey(
                blank=True,
                help_text="Third",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="integration.third",
                verbose_name="Third",
            ),
        ),
    ]
