# Generated by Django 4.2.7 on 2024-03-16 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveDirectoryCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                ("status", models.BooleanField(default=True, help_text="Object status", verbose_name="Status")),
                (
                    "domain",
                    models.CharField(help_text="Active Directory domain", max_length=255, verbose_name="Domain"),
                ),
                (
                    "domain_extension",
                    models.CharField(
                        help_text="Active Directory domain extension", max_length=255, verbose_name="Domain Extension"
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="Active Directory username", max_length=255, verbose_name="Username"),
                ),
                (
                    "password",
                    models.CharField(help_text="Active Directory password", max_length=255, verbose_name="Password"),
                ),
            ],
            options={
                "verbose_name": "Active Directory Credential",
                "verbose_name_plural": "Active Directory Credentialss",
            },
        ),
        migrations.CreateModel(
            name="OrganizationalUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                ("status", models.BooleanField(default=True, help_text="Object status", verbose_name="Status")),
                (
                    "OU",
                    models.CharField(
                        help_text="Active Directory Organizational Unit",
                        max_length=255,
                        verbose_name="Organizational Unit",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        help_text="Active Directory credential",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maloka_da.activedirectorycredential",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Unit",
                "verbose_name_plural": "Organizational Units",
            },
        ),
        migrations.CreateModel(
            name="ActiveDirectoryUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                ("status", models.BooleanField(default=True, help_text="Object status", verbose_name="Status")),
                (
                    "name",
                    models.CharField(help_text="Active Directory user name", max_length=255, verbose_name="Name"),
                ),
                ("user", models.CharField(help_text="Active Directory user", max_length=255, verbose_name="User")),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        help_text="Active Directory Organizational Unit",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maloka_da.organizationalunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Directory User",
                "verbose_name_plural": "Active Directory Users",
            },
        ),
        migrations.AddConstraint(
            model_name="activedirectorycredential",
            constraint=models.CheckConstraint(
                check=models.Q(("domain__isnull", False), ("domain_extension__isnull", False)),
                name="maloka_da_activedirectorycredential_both_fields_not_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activedirectorycredential",
            unique_together={("domain", "domain_extension")},
        ),
    ]
