# Generated by Django 4.2.7 on 2024-03-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maloka_da", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activedirectoryuser",
            name="area",
            field=models.CharField(
                blank=True, help_text="Active Directory user area", max_length=255, verbose_name="Area"
            ),
        ),
        migrations.AddField(
            model_name="activedirectoryuser",
            name="role",
            field=models.CharField(
                blank=True, help_text="Active Directory user role", max_length=255, verbose_name="Role"
            ),
        ),
        migrations.AddField(
            model_name="activedirectoryuser",
            name="security_group",
            field=models.CharField(
                blank=True,
                help_text="Active Directory user security group",
                max_length=255,
                verbose_name="Security Group",
            ),
        ),
    ]
