# Generated by Django 4.2.7 on 2024-03-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maloka_da", "0002_activedirectoryuser_area_activedirectoryuser_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activedirectoryuser",
            name="position",
            field=models.CharField(
                blank=True, help_text="Active Directory user position", max_length=255, verbose_name="Position"
            ),
        ),
    ]
