# Generated by Django 4.2.7 on 2023-11-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveIntegration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(help_text="Name of the integration", max_length=50, verbose_name="Name")),
                (
                    "code",
                    models.SlugField(
                        help_text="Code of the integration", max_length=10, unique=True, verbose_name="Code"
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Integration",
                "verbose_name_plural": "Active Integrations",
            },
        ),
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "IdTipCen",
                    models.CharField(
                        blank=True, help_text="IdTipCen", max_length=150, null=True, verbose_name="IdTipCen"
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(blank=True, help_text="Nombre", max_length=150, null=True, verbose_name="Nombre"),
                ),
                (
                    "Nemoni",
                    models.CharField(blank=True, help_text="Nemoni", max_length=150, null=True, verbose_name="Nemoni"),
                ),
                (
                    "IdUsuari",
                    models.CharField(
                        blank=True, help_text="IdUsuari", max_length=150, null=True, verbose_name="IdUsuari"
                    ),
                ),
                (
                    "Operac",
                    models.CharField(blank=True, help_text="Operac", max_length=150, null=True, verbose_name="Operac"),
                ),
                (
                    "FecMod",
                    models.CharField(blank=True, help_text="FecMod", max_length=150, null=True, verbose_name="FecMod"),
                ),
            ],
            options={
                "verbose_name": "Business Unit",
                "verbose_name_plural": "Business Units",
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "IdEmpres",
                    models.CharField(
                        blank=True, help_text="IdEmpres", max_length=150, null=True, verbose_name="IdEmpres"
                    ),
                ),
                (
                    "IdSucurs",
                    models.CharField(
                        blank=True, help_text="IdSucurs", max_length=150, null=True, verbose_name="IdSucurs"
                    ),
                ),
                (
                    "IdCenCos",
                    models.CharField(
                        blank=True, help_text="IdCenCos", max_length=150, null=True, verbose_name="IdCenCos"
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(blank=True, help_text="Nombre", max_length=150, null=True, verbose_name="Nombre"),
                ),
                (
                    "Nemoni",
                    models.CharField(blank=True, help_text="Nemoni", max_length=150, null=True, verbose_name="Nemoni"),
                ),
                (
                    "IdTipCen",
                    models.CharField(
                        blank=True, help_text="IdTipCen", max_length=150, null=True, verbose_name="IdTipCen"
                    ),
                ),
                (
                    "IdSubcue",
                    models.CharField(
                        blank=True, help_text="IdSubcue", max_length=150, null=True, verbose_name="IdSubcue"
                    ),
                ),
                (
                    "IdConGas",
                    models.CharField(
                        blank=True, help_text="IdConGas", max_length=150, null=True, verbose_name="IdConGas"
                    ),
                ),
                (
                    "IdTipCenCos",
                    models.CharField(
                        blank=True, help_text="IdTipCenCos", max_length=150, null=True, verbose_name="IdTipCenCos"
                    ),
                ),
                (
                    "NivAccDat",
                    models.CharField(
                        blank=True, help_text="NivAccDat", max_length=150, null=True, verbose_name="NivAccDat"
                    ),
                ),
                (
                    "IdUsuari",
                    models.CharField(
                        blank=True, help_text="IdUsuari", max_length=150, null=True, verbose_name="IdUsuari"
                    ),
                ),
                (
                    "Operac",
                    models.CharField(blank=True, help_text="Operac", max_length=150, null=True, verbose_name="Operac"),
                ),
                (
                    "FecMod",
                    models.CharField(blank=True, help_text="FecMod", max_length=150, null=True, verbose_name="FecMod"),
                ),
            ],
            options={
                "verbose_name": "Cost Center",
                "verbose_name_plural": "Cost Centers",
            },
        ),
        migrations.CreateModel(
            name="ExpenseConcept",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "IdConGas",
                    models.CharField(
                        blank=True, help_text="IdConGas", max_length=150, null=True, verbose_name="IdConGas"
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(blank=True, help_text="Nombre", max_length=150, null=True, verbose_name="Nombre"),
                ),
                (
                    "Nemoni",
                    models.CharField(blank=True, help_text="Nemoni", max_length=150, null=True, verbose_name="Nemoni"),
                ),
                (
                    "TipoPresup",
                    models.CharField(
                        blank=True, help_text="TipoPresup", max_length=150, null=True, verbose_name="TipoPresup"
                    ),
                ),
                (
                    "IdRetFte",
                    models.CharField(
                        blank=True, help_text="IdRetFte", max_length=150, null=True, verbose_name="IdRetFte"
                    ),
                ),
                (
                    "IdTipGas",
                    models.CharField(
                        blank=True, help_text="IdTipGas", max_length=150, null=True, verbose_name="IdTipGas"
                    ),
                ),
                (
                    "IdConGasDistrib",
                    models.CharField(
                        blank=True,
                        help_text="IdConGasDistrib",
                        max_length=150,
                        null=True,
                        verbose_name="IdConGasDistrib",
                    ),
                ),
                (
                    "CtGtoCauPag",
                    models.CharField(
                        blank=True, help_text="CtGtoCauPag", max_length=150, null=True, verbose_name="CtGtoCauPag"
                    ),
                ),
                (
                    "ECtGtoCauPag",
                    models.CharField(
                        blank=True, help_text="ECtGtoCauPag", max_length=150, null=True, verbose_name="ECtGtoCauPag"
                    ),
                ),
                (
                    "IdTipIVA",
                    models.CharField(
                        blank=True, help_text="IdTipIVA", max_length=150, null=True, verbose_name="IdTipIVA"
                    ),
                ),
                (
                    "PorIva",
                    models.CharField(blank=True, help_text="PorIva", max_length=150, null=True, verbose_name="PorIva"),
                ),
                (
                    "CodEquival",
                    models.CharField(
                        blank=True, help_text="CodEquival", max_length=150, null=True, verbose_name="CodEquival"
                    ),
                ),
                (
                    "CtGastos",
                    models.CharField(
                        blank=True, help_text="CtGastos", max_length=150, null=True, verbose_name="CtGastos"
                    ),
                ),
                (
                    "ECtGastos",
                    models.CharField(
                        blank=True, help_text="ECtGastos", max_length=150, null=True, verbose_name="ECtGastos"
                    ),
                ),
                (
                    "EsBaseImpto",
                    models.CharField(
                        blank=True, help_text="EsBaseImpto", max_length=150, null=True, verbose_name="EsBaseImpto"
                    ),
                ),
                (
                    "ValorBase",
                    models.CharField(
                        blank=True, help_text="ValorBase", max_length=150, null=True, verbose_name="ValorBase"
                    ),
                ),
                (
                    "ValorMax",
                    models.CharField(
                        blank=True, help_text="ValorMax", max_length=150, null=True, verbose_name="ValorMax"
                    ),
                ),
                (
                    "IdConMedMag",
                    models.CharField(
                        blank=True, help_text="IdConMedMag", max_length=150, null=True, verbose_name="IdConMedMag"
                    ),
                ),
                (
                    "Campo1",
                    models.CharField(blank=True, help_text="Campo1", max_length=150, null=True, verbose_name="Campo1"),
                ),
                (
                    "IdUsuari",
                    models.CharField(
                        blank=True, help_text="IdUsuari", max_length=150, null=True, verbose_name="IdUsuari"
                    ),
                ),
                (
                    "Operac",
                    models.CharField(blank=True, help_text="Operac", max_length=150, null=True, verbose_name="Operac"),
                ),
                (
                    "FecMod",
                    models.CharField(blank=True, help_text="FecMod", max_length=150, null=True, verbose_name="FecMod"),
                ),
            ],
            options={
                "verbose_name": "Expense Concept",
                "verbose_name_plural": "Expense Concepts",
            },
        ),
        migrations.CreateModel(
            name="ExpenseType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "IdTipGas",
                    models.CharField(
                        blank=True, help_text="IdTipGas", max_length=150, null=True, verbose_name="IdTipGas"
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(blank=True, help_text="Nombre", max_length=150, null=True, verbose_name="Nombre"),
                ),
                (
                    "Nemoni",
                    models.CharField(blank=True, help_text="Nemoni", max_length=150, null=True, verbose_name="Nemoni"),
                ),
                (
                    "ClaseTipGas",
                    models.CharField(
                        blank=True, help_text="ClaseTipGas", max_length=150, null=True, verbose_name="ClaseTipGas"
                    ),
                ),
                (
                    "IdOpeGas",
                    models.CharField(
                        blank=True, help_text="IdOpeGas", max_length=150, null=True, verbose_name="IdOpeGas"
                    ),
                ),
                (
                    "IdUsuari",
                    models.CharField(
                        blank=True, help_text="IdUsuari", max_length=150, null=True, verbose_name="IdUsuari"
                    ),
                ),
                (
                    "Operac",
                    models.CharField(blank=True, help_text="Operac", max_length=150, null=True, verbose_name="Operac"),
                ),
                (
                    "FecMod",
                    models.CharField(blank=True, help_text="FecMod", max_length=150, null=True, verbose_name="FecMod"),
                ),
            ],
            options={
                "verbose_name": "Expense Type",
                "verbose_name_plural": "Expense Types",
            },
        ),
        migrations.CreateModel(
            name="Third",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "IdEmpres",
                    models.CharField(
                        blank=True, help_text="IdEmpres", max_length=150, null=True, verbose_name="IdEmpres"
                    ),
                ),
                (
                    "IdSucurs",
                    models.CharField(
                        blank=True, help_text="IdSucurs", max_length=150, null=True, verbose_name="IdSucurs"
                    ),
                ),
                (
                    "IdTercer",
                    models.CharField(
                        blank=True, help_text="IdTercer", max_length=150, null=True, verbose_name="IdTercer"
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(blank=True, help_text="Nombre", max_length=150, null=True, verbose_name="Nombre"),
                ),
                (
                    "Razon",
                    models.CharField(blank=True, help_text="Razon", max_length=150, null=True, verbose_name="Razon"),
                ),
                (
                    "TipoId",
                    models.CharField(blank=True, help_text="TipoId", max_length=150, null=True, verbose_name="TipoId"),
                ),
                ("Nit", models.CharField(blank=True, help_text="Nit", max_length=150, null=True, verbose_name="Nit")),
                (
                    "Direcc",
                    models.CharField(blank=True, help_text="Direcc", max_length=150, null=True, verbose_name="Direcc"),
                ),
                (
                    "Telefo",
                    models.CharField(blank=True, help_text="Telefo", max_length=150, null=True, verbose_name="Telefo"),
                ),
                ("Fax", models.CharField(blank=True, help_text="Fax", max_length=150, null=True, verbose_name="Fax")),
                (
                    "Ciudad",
                    models.CharField(blank=True, help_text="Ciudad", max_length=150, null=True, verbose_name="Ciudad"),
                ),
                (
                    "Pais",
                    models.CharField(blank=True, help_text="Pais", max_length=150, null=True, verbose_name="Pais"),
                ),
                (
                    "Contac",
                    models.CharField(blank=True, help_text="Contac", max_length=150, null=True, verbose_name="Contac"),
                ),
                (
                    "TelContac",
                    models.CharField(
                        blank=True, help_text="TelContac", max_length=150, null=True, verbose_name="TelContac"
                    ),
                ),
                (
                    "Observ",
                    models.CharField(blank=True, help_text="Observ", max_length=150, null=True, verbose_name="Observ"),
                ),
                (
                    "IdViades",
                    models.CharField(
                        blank=True, help_text="IdViades", max_length=150, null=True, verbose_name="IdViades"
                    ),
                ),
                (
                    "IdCodVen",
                    models.CharField(
                        blank=True, help_text="IdCodVen", max_length=150, null=True, verbose_name="IdCodVen"
                    ),
                ),
                (
                    "IdCajBan",
                    models.CharField(
                        blank=True, help_text="IdCajBan", max_length=150, null=True, verbose_name="IdCajBan"
                    ),
                ),
                (
                    "TipoCta",
                    models.CharField(
                        blank=True, help_text="TipoCta", max_length=150, null=True, verbose_name="TipoCta"
                    ),
                ),
                (
                    "NroCuenta",
                    models.CharField(
                        blank=True, help_text="NroCuenta", max_length=150, null=True, verbose_name="NroCuenta"
                    ),
                ),
                (
                    "CupoAsig",
                    models.CharField(
                        blank=True, help_text="CupoAsig", max_length=150, null=True, verbose_name="CupoAsig"
                    ),
                ),
                (
                    "CupoDisp",
                    models.CharField(
                        blank=True, help_text="CupoDisp", max_length=150, null=True, verbose_name="CupoDisp"
                    ),
                ),
                (
                    "FecIngreso",
                    models.CharField(
                        blank=True, help_text="FecIngreso", max_length=150, null=True, verbose_name="FecIngreso"
                    ),
                ),
                (
                    "PorDesc",
                    models.CharField(
                        blank=True, help_text="PorDesc", max_length=150, null=True, verbose_name="PorDesc"
                    ),
                ),
                (
                    "PorRecargo",
                    models.CharField(
                        blank=True, help_text="PorRecargo", max_length=150, null=True, verbose_name="PorRecargo"
                    ),
                ),
                (
                    "PorTarjeta",
                    models.CharField(
                        blank=True, help_text="PorTarjeta", max_length=150, null=True, verbose_name="PorTarjeta"
                    ),
                ),
                (
                    "PorVenta",
                    models.CharField(
                        blank=True, help_text="PorVenta", max_length=150, null=True, verbose_name="PorVenta"
                    ),
                ),
                (
                    "PorCobro",
                    models.CharField(
                        blank=True, help_text="PorCobro", max_length=150, null=True, verbose_name="PorCobro"
                    ),
                ),
                (
                    "ClaseA",
                    models.CharField(blank=True, help_text="ClaseA", max_length=150, null=True, verbose_name="ClaseA"),
                ),
                (
                    "ClaseB",
                    models.CharField(blank=True, help_text="ClaseB", max_length=150, null=True, verbose_name="ClaseB"),
                ),
                (
                    "ClaseC",
                    models.CharField(blank=True, help_text="ClaseC", max_length=150, null=True, verbose_name="ClaseC"),
                ),
                (
                    "ClaseD",
                    models.CharField(blank=True, help_text="ClaseD", max_length=150, null=True, verbose_name="ClaseD"),
                ),
                (
                    "ClaseE",
                    models.CharField(blank=True, help_text="ClaseE", max_length=150, null=True, verbose_name="ClaseE"),
                ),
                ("Url", models.CharField(blank=True, help_text="Url", max_length=250, null=True, verbose_name="Url")),
                (
                    "IdAgeIva",
                    models.CharField(
                        blank=True, help_text="IdAgeIva", max_length=150, null=True, verbose_name="IdAgeIva"
                    ),
                ),
                (
                    "IdAgeIca",
                    models.CharField(
                        blank=True, help_text="IdAgeIca", max_length=150, null=True, verbose_name="IdAgeIca"
                    ),
                ),
                (
                    "IdActIca",
                    models.CharField(
                        blank=True, help_text="IdActIca", max_length=150, null=True, verbose_name="IdActIca"
                    ),
                ),
                (
                    "Autoreten",
                    models.CharField(
                        blank=True, help_text="Autoreten", max_length=150, null=True, verbose_name="Autoreten"
                    ),
                ),
                (
                    "SujRetFte",
                    models.CharField(
                        blank=True, help_text="SujRetFte", max_length=150, null=True, verbose_name="SujRetFte"
                    ),
                ),
                (
                    "IdVended",
                    models.CharField(
                        blank=True, help_text="IdVended", max_length=150, null=True, verbose_name="IdVended"
                    ),
                ),
                (
                    "IdLisPre",
                    models.CharField(
                        blank=True, help_text="IdLisPre", max_length=150, null=True, verbose_name="IdLisPre"
                    ),
                ),
                (
                    "NivAccDat",
                    models.CharField(
                        blank=True, help_text="NivAccDat", max_length=150, null=True, verbose_name="NivAccDat"
                    ),
                ),
                (
                    "SujRetCREE",
                    models.CharField(
                        blank=True, help_text="SujRetCREE", max_length=150, null=True, verbose_name="SujRetCREE"
                    ),
                ),
                (
                    "PriApell",
                    models.CharField(
                        blank=True, help_text="PriApell", max_length=150, null=True, verbose_name="PriApell"
                    ),
                ),
                (
                    "SegApell",
                    models.CharField(
                        blank=True, help_text="SegApell", max_length=150, null=True, verbose_name="SegApell"
                    ),
                ),
                (
                    "PriNombre",
                    models.CharField(
                        blank=True, help_text="PriNombre", max_length=150, null=True, verbose_name="PriNombre"
                    ),
                ),
                (
                    "OtrosNom",
                    models.CharField(
                        blank=True, help_text="OtrosNom", max_length=150, null=True, verbose_name="OtrosNom"
                    ),
                ),
                (
                    "IdBarrio",
                    models.CharField(
                        blank=True, help_text="IdBarrio", max_length=150, null=True, verbose_name="IdBarrio"
                    ),
                ),
                (
                    "IdSector",
                    models.CharField(
                        blank=True, help_text="IdSector", max_length=150, null=True, verbose_name="IdSector"
                    ),
                ),
                (
                    "IngAnuales",
                    models.CharField(
                        blank=True, help_text="IngAnuales", max_length=150, null=True, verbose_name="IngAnuales"
                    ),
                ),
                (
                    "NumEmp",
                    models.CharField(blank=True, help_text="NumEmp", max_length=150, null=True, verbose_name="NumEmp"),
                ),
                (
                    "PaginaWeb",
                    models.CharField(
                        blank=True, help_text="PaginaWeb", max_length=150, null=True, verbose_name="PaginaWeb"
                    ),
                ),
                (
                    "CanalEntrega",
                    models.CharField(
                        blank=True, help_text="CanalEntrega", max_length=150, null=True, verbose_name="CanalEntrega"
                    ),
                ),
                (
                    "MatMercantil",
                    models.CharField(
                        blank=True, help_text="MatMercantil", max_length=150, null=True, verbose_name="MatMercantil"
                    ),
                ),
                (
                    "IdRespFiscal",
                    models.CharField(
                        blank=True, help_text="IdRespFiscal", max_length=150, null=True, verbose_name="IdRespFiscal"
                    ),
                ),
                (
                    "Correo2",
                    models.CharField(
                        blank=True, help_text="Correo2", max_length=150, null=True, verbose_name="Correo2"
                    ),
                ),
                (
                    "Correo3",
                    models.CharField(
                        blank=True, help_text="Correo3", max_length=150, null=True, verbose_name="Correo3"
                    ),
                ),
                (
                    "Campo20",
                    models.CharField(
                        blank=True, help_text="Campo20", max_length=150, null=True, verbose_name="Campo20"
                    ),
                ),
                (
                    "IdUsuari",
                    models.CharField(
                        blank=True, help_text="IdUsuari", max_length=150, null=True, verbose_name="IdUsuari"
                    ),
                ),
                (
                    "Operac",
                    models.CharField(blank=True, help_text="Operac", max_length=150, null=True, verbose_name="Operac"),
                ),
                (
                    "FecMod",
                    models.CharField(blank=True, help_text="FecMod", max_length=150, null=True, verbose_name="FecMod"),
                ),
            ],
            options={
                "verbose_name": "Third",
                "verbose_name_plural": "Thirds",
            },
        ),
    ]
