# Generated by Django 4.2.5 on 2023-09-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessunit",
            name="code",
        ),
        migrations.RemoveField(
            model_name="businessunit",
            name="name",
        ),
        migrations.RemoveField(
            model_name="costcenter",
            name="code",
        ),
        migrations.RemoveField(
            model_name="costcenter",
            name="name",
        ),
        migrations.RemoveField(
            model_name="expensetype",
            name="code",
        ),
        migrations.RemoveField(
            model_name="expensetype",
            name="name",
        ),
        migrations.RemoveField(
            model_name="third",
            name="code",
        ),
        migrations.RemoveField(
            model_name="third",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="third",
            name="last_name",
        ),
        migrations.AddField(
            model_name="businessunit",
            name="Campo1",
            field=models.CharField(blank=True, help_text="Campo1", max_length=150, null=True, verbose_name="Campo1"),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="CodEquival",
            field=models.CharField(
                blank=True, help_text="CodEquival", max_length=150, null=True, verbose_name="CodEquival"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="CtGastos",
            field=models.CharField(
                blank=True, help_text="CtGastos", max_length=150, null=True, verbose_name="CtGastos"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="CtGtoCauPag",
            field=models.CharField(
                blank=True, help_text="CtGtoCauPag", max_length=150, null=True, verbose_name="CtGtoCauPag"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="ECtGastos",
            field=models.CharField(
                blank=True, help_text="ECtGastos", max_length=150, null=True, verbose_name="ECtGastos"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="ECtGtoCauPag",
            field=models.CharField(
                blank=True, help_text="ECtGtoCauPag", max_length=150, null=True, verbose_name="ECtGtoCauPag"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="EsBaseImpto",
            field=models.CharField(
                blank=True, help_text="EsBaseImpto", max_length=150, null=True, verbose_name="EsBaseImpto"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="FecMod",
            field=models.CharField(blank=True, help_text="FecMod", max_length=150, null=True, verbose_name="FecMod"),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="IdConGas",
            field=models.CharField(
                blank=True, help_text="IdConGas", max_length=150, null=True, verbose_name="IdConGas"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="IdConGasDistrib",
            field=models.CharField(
                blank=True, help_text="IdConGasDistrib", max_length=150, null=True, verbose_name="IdConGasDistrib"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="IdConMedMag",
            field=models.CharField(
                blank=True, help_text="IdConMedMag", max_length=150, null=True, verbose_name="IdConMedMag"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="IdRetFte",
            field=models.CharField(
                blank=True, help_text="IdRetFte", max_length=150, null=True, verbose_name="IdRetFte"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="IdTipGas",
            field=models.CharField(
                blank=True, help_text="IdTipGas", max_length=150, null=True, verbose_name="IdTipGas"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="IdTipIVA",
            field=models.CharField(
                blank=True, help_text="IdTipIVA", max_length=150, null=True, verbose_name="IdTipIVA"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="IdUsuari",
            field=models.CharField(
                blank=True, help_text="IdUsuari", max_length=150, null=True, verbose_name="IdUsuari"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="Nemoni",
            field=models.CharField(blank=True, help_text="Nemoni", max_length=150, null=True, verbose_name="Nemoni"),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="Nombre",
            field=models.CharField(blank=True, help_text="Nombre", max_length=150, null=True, verbose_name="Nombre"),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="Operac",
            field=models.CharField(blank=True, help_text="Operac", max_length=150, null=True, verbose_name="Operac"),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="PorIva",
            field=models.CharField(blank=True, help_text="PorIva", max_length=150, null=True, verbose_name="PorIva"),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="TipoPresup",
            field=models.CharField(
                blank=True, help_text="TipoPresup", max_length=150, null=True, verbose_name="TipoPresup"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="ValorBase",
            field=models.CharField(
                blank=True, help_text="ValorBase", max_length=150, null=True, verbose_name="ValorBase"
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="ValorMax",
            field=models.CharField(
                blank=True, help_text="ValorMax", max_length=150, null=True, verbose_name="ValorMax"
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="FecMod",
            field=models.CharField(blank=True, help_text="FecMod", max_length=150, null=True, verbose_name="FecMod"),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="IdCenCos",
            field=models.CharField(
                blank=True, help_text="IdCenCos", max_length=150, null=True, verbose_name="IdCenCos"
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="IdConGas",
            field=models.CharField(
                blank=True, help_text="IdConGas", max_length=150, null=True, verbose_name="IdConGas"
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="IdEmpres",
            field=models.CharField(
                blank=True, help_text="IdEmpres", max_length=150, null=True, verbose_name="IdEmpres"
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="IdSubcue",
            field=models.CharField(
                blank=True, help_text="IdSubcue", max_length=150, null=True, verbose_name="IdSubcue"
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="IdSucurs",
            field=models.CharField(
                blank=True, help_text="IdSucurs", max_length=150, null=True, verbose_name="IdSucurs"
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="IdTipCen",
            field=models.CharField(
                blank=True, help_text="IdTipCen", max_length=150, null=True, verbose_name="IdTipCen"
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="IdTipCenCos",
            field=models.CharField(
                blank=True, help_text="IdTipCenCos", max_length=150, null=True, verbose_name="IdTipCenCos"
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="IdUsuari",
            field=models.CharField(
                blank=True, help_text="IdUsuari", max_length=150, null=True, verbose_name="IdUsuari"
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="Nemoni",
            field=models.CharField(blank=True, help_text="Nemoni", max_length=150, null=True, verbose_name="Nemoni"),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="NivAccDat",
            field=models.CharField(
                blank=True, help_text="NivAccDat", max_length=150, null=True, verbose_name="NivAccDat"
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="Nombre",
            field=models.CharField(blank=True, help_text="Nombre", max_length=150, null=True, verbose_name="Nombre"),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="Operac",
            field=models.CharField(blank=True, help_text="Operac", max_length=150, null=True, verbose_name="Operac"),
        ),
        migrations.AddField(
            model_name="expensetype",
            name="ClaseTipGas",
            field=models.CharField(
                blank=True, help_text="ClaseTipGas", max_length=150, null=True, verbose_name="ClaseTipGas"
            ),
        ),
        migrations.AddField(
            model_name="expensetype",
            name="FecMod",
            field=models.CharField(blank=True, help_text="FecMod", max_length=150, null=True, verbose_name="FecMod"),
        ),
        migrations.AddField(
            model_name="expensetype",
            name="IdOpeGas",
            field=models.CharField(
                blank=True, help_text="IdOpeGas", max_length=150, null=True, verbose_name="IdOpeGas"
            ),
        ),
        migrations.AddField(
            model_name="expensetype",
            name="IdTipGas",
            field=models.CharField(
                blank=True, help_text="IdTipGas", max_length=150, null=True, verbose_name="IdTipGas"
            ),
        ),
        migrations.AddField(
            model_name="expensetype",
            name="IdUsuari",
            field=models.CharField(
                blank=True, help_text="IdUsuari", max_length=150, null=True, verbose_name="IdUsuari"
            ),
        ),
        migrations.AddField(
            model_name="expensetype",
            name="Nemoni",
            field=models.CharField(blank=True, help_text="Nemoni", max_length=150, null=True, verbose_name="Nemoni"),
        ),
        migrations.AddField(
            model_name="expensetype",
            name="Nombre",
            field=models.CharField(blank=True, help_text="Nombre", max_length=150, null=True, verbose_name="Nombre"),
        ),
        migrations.AddField(
            model_name="expensetype",
            name="Operac",
            field=models.CharField(blank=True, help_text="Operac", max_length=150, null=True, verbose_name="Operac"),
        ),
        migrations.AddField(
            model_name="third",
            name="Autoreten",
            field=models.CharField(
                blank=True, help_text="Autoreten", max_length=150, null=True, verbose_name="Autoreten"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="Campo20",
            field=models.CharField(blank=True, help_text="Campo20", max_length=150, null=True, verbose_name="Campo20"),
        ),
        migrations.AddField(
            model_name="third",
            name="CanalEntrega",
            field=models.CharField(
                blank=True, help_text="CanalEntrega", max_length=150, null=True, verbose_name="CanalEntrega"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="Ciudad",
            field=models.CharField(blank=True, help_text="Ciudad", max_length=150, null=True, verbose_name="Ciudad"),
        ),
        migrations.AddField(
            model_name="third",
            name="ClaseA",
            field=models.CharField(blank=True, help_text="ClaseA", max_length=150, null=True, verbose_name="ClaseA"),
        ),
        migrations.AddField(
            model_name="third",
            name="ClaseB",
            field=models.CharField(blank=True, help_text="ClaseB", max_length=150, null=True, verbose_name="ClaseB"),
        ),
        migrations.AddField(
            model_name="third",
            name="ClaseC",
            field=models.CharField(blank=True, help_text="ClaseC", max_length=150, null=True, verbose_name="ClaseC"),
        ),
        migrations.AddField(
            model_name="third",
            name="ClaseD",
            field=models.CharField(blank=True, help_text="ClaseD", max_length=150, null=True, verbose_name="ClaseD"),
        ),
        migrations.AddField(
            model_name="third",
            name="ClaseE",
            field=models.CharField(blank=True, help_text="ClaseE", max_length=150, null=True, verbose_name="ClaseE"),
        ),
        migrations.AddField(
            model_name="third",
            name="Contac",
            field=models.CharField(blank=True, help_text="Contac", max_length=150, null=True, verbose_name="Contac"),
        ),
        migrations.AddField(
            model_name="third",
            name="Correo2",
            field=models.CharField(blank=True, help_text="Correo2", max_length=150, null=True, verbose_name="Correo2"),
        ),
        migrations.AddField(
            model_name="third",
            name="Correo3",
            field=models.CharField(blank=True, help_text="Correo3", max_length=150, null=True, verbose_name="Correo3"),
        ),
        migrations.AddField(
            model_name="third",
            name="CupoAsig",
            field=models.CharField(
                blank=True, help_text="CupoAsig", max_length=150, null=True, verbose_name="CupoAsig"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="CupoDisp",
            field=models.CharField(
                blank=True, help_text="CupoDisp", max_length=150, null=True, verbose_name="CupoDisp"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="Direcc",
            field=models.CharField(blank=True, help_text="Direcc", max_length=150, null=True, verbose_name="Direcc"),
        ),
        migrations.AddField(
            model_name="third",
            name="Fax",
            field=models.CharField(blank=True, help_text="Fax", max_length=150, null=True, verbose_name="Fax"),
        ),
        migrations.AddField(
            model_name="third",
            name="FecIngreso",
            field=models.CharField(
                blank=True, help_text="FecIngreso", max_length=150, null=True, verbose_name="FecIngreso"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="FecMod",
            field=models.CharField(blank=True, help_text="FecMod", max_length=150, null=True, verbose_name="FecMod"),
        ),
        migrations.AddField(
            model_name="third",
            name="IdActIca",
            field=models.CharField(
                blank=True, help_text="IdActIca", max_length=150, null=True, verbose_name="IdActIca"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdAgeIca",
            field=models.CharField(
                blank=True, help_text="IdAgeIca", max_length=150, null=True, verbose_name="IdAgeIca"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdAgeIva",
            field=models.CharField(
                blank=True, help_text="IdAgeIva", max_length=150, null=True, verbose_name="IdAgeIva"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdBarrio",
            field=models.CharField(
                blank=True, help_text="IdBarrio", max_length=150, null=True, verbose_name="IdBarrio"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdCajBan",
            field=models.CharField(
                blank=True, help_text="IdCajBan", max_length=150, null=True, verbose_name="IdCajBan"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdCodVen",
            field=models.CharField(
                blank=True, help_text="IdCodVen", max_length=150, null=True, verbose_name="IdCodVen"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdEmpres",
            field=models.CharField(
                blank=True, help_text="IdEmpres", max_length=150, null=True, verbose_name="IdEmpres"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdLisPre",
            field=models.CharField(
                blank=True, help_text="IdLisPre", max_length=150, null=True, verbose_name="IdLisPre"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdRespFiscal",
            field=models.CharField(
                blank=True, help_text="IdRespFiscal", max_length=150, null=True, verbose_name="IdRespFiscal"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdSector",
            field=models.CharField(
                blank=True, help_text="IdSector", max_length=150, null=True, verbose_name="IdSector"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdSucurs",
            field=models.CharField(
                blank=True, help_text="IdSucurs", max_length=150, null=True, verbose_name="IdSucurs"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdTercer",
            field=models.CharField(
                blank=True, help_text="IdTercer", max_length=150, null=True, verbose_name="IdTercer"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdUsuari",
            field=models.CharField(
                blank=True, help_text="IdUsuari", max_length=150, null=True, verbose_name="IdUsuari"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdVended",
            field=models.CharField(
                blank=True, help_text="IdVended", max_length=150, null=True, verbose_name="IdVended"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IdViades",
            field=models.CharField(
                blank=True, help_text="IdViades", max_length=150, null=True, verbose_name="IdViades"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="IngAnuales",
            field=models.CharField(
                blank=True, help_text="IngAnuales", max_length=150, null=True, verbose_name="IngAnuales"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="MatMercantil",
            field=models.CharField(
                blank=True, help_text="MatMercantil", max_length=150, null=True, verbose_name="MatMercantil"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="Nit",
            field=models.CharField(blank=True, help_text="Nit", max_length=150, null=True, verbose_name="Nit"),
        ),
        migrations.AddField(
            model_name="third",
            name="NivAccDat",
            field=models.CharField(
                blank=True, help_text="NivAccDat", max_length=150, null=True, verbose_name="NivAccDat"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="Nombre",
            field=models.CharField(blank=True, help_text="Nombre", max_length=150, null=True, verbose_name="Nombre"),
        ),
        migrations.AddField(
            model_name="third",
            name="NroCuenta",
            field=models.CharField(
                blank=True, help_text="NroCuenta", max_length=150, null=True, verbose_name="NroCuenta"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="NumEmp",
            field=models.CharField(blank=True, help_text="NumEmp", max_length=150, null=True, verbose_name="NumEmp"),
        ),
        migrations.AddField(
            model_name="third",
            name="Observ",
            field=models.CharField(blank=True, help_text="Observ", max_length=150, null=True, verbose_name="Observ"),
        ),
        migrations.AddField(
            model_name="third",
            name="Operac",
            field=models.CharField(blank=True, help_text="Operac", max_length=150, null=True, verbose_name="Operac"),
        ),
        migrations.AddField(
            model_name="third",
            name="OtrosNom",
            field=models.CharField(
                blank=True, help_text="OtrosNom", max_length=150, null=True, verbose_name="OtrosNom"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="PaginaWeb",
            field=models.CharField(
                blank=True, help_text="PaginaWeb", max_length=150, null=True, verbose_name="PaginaWeb"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="Pais",
            field=models.CharField(blank=True, help_text="Pais", max_length=150, null=True, verbose_name="Pais"),
        ),
        migrations.AddField(
            model_name="third",
            name="PorCobro",
            field=models.CharField(
                blank=True, help_text="PorCobro", max_length=150, null=True, verbose_name="PorCobro"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="PorDesc",
            field=models.CharField(blank=True, help_text="PorDesc", max_length=150, null=True, verbose_name="PorDesc"),
        ),
        migrations.AddField(
            model_name="third",
            name="PorRecargo",
            field=models.CharField(
                blank=True, help_text="PorRecargo", max_length=150, null=True, verbose_name="PorRecargo"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="PorTarjeta",
            field=models.CharField(
                blank=True, help_text="PorTarjeta", max_length=150, null=True, verbose_name="PorTarjeta"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="PorVenta",
            field=models.CharField(
                blank=True, help_text="PorVenta", max_length=150, null=True, verbose_name="PorVenta"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="PriApell",
            field=models.CharField(
                blank=True, help_text="PriApell", max_length=150, null=True, verbose_name="PriApell"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="PriNombre",
            field=models.CharField(
                blank=True, help_text="PriNombre", max_length=150, null=True, verbose_name="PriNombre"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="Razon",
            field=models.CharField(blank=True, help_text="Razon", max_length=150, null=True, verbose_name="Razon"),
        ),
        migrations.AddField(
            model_name="third",
            name="SegApell",
            field=models.CharField(
                blank=True, help_text="SegApell", max_length=150, null=True, verbose_name="SegApell"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="SujRetCREE",
            field=models.CharField(
                blank=True, help_text="SujRetCREE", max_length=150, null=True, verbose_name="SujRetCREE"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="SujRetFte",
            field=models.CharField(
                blank=True, help_text="SujRetFte", max_length=150, null=True, verbose_name="SujRetFte"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="TelContac",
            field=models.CharField(
                blank=True, help_text="TelContac", max_length=150, null=True, verbose_name="TelContac"
            ),
        ),
        migrations.AddField(
            model_name="third",
            name="Telefo",
            field=models.CharField(blank=True, help_text="Telefo", max_length=150, null=True, verbose_name="Telefo"),
        ),
        migrations.AddField(
            model_name="third",
            name="TipoCta",
            field=models.CharField(blank=True, help_text="TipoCta", max_length=150, null=True, verbose_name="TipoCta"),
        ),
        migrations.AddField(
            model_name="third",
            name="TipoId",
            field=models.CharField(blank=True, help_text="TipoId", max_length=150, null=True, verbose_name="TipoId"),
        ),
        migrations.AddField(
            model_name="third",
            name="Url",
            field=models.CharField(blank=True, help_text="Url", max_length=250, null=True, verbose_name="Url"),
        ),
    ]
