# Generated by Django 4.2.5 on 2023-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0002_remove_businessunit_code_remove_businessunit_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveIntegration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(help_text="Name of the integration", max_length=50, verbose_name="Name")),
                (
                    "code",
                    models.SlugField(
                        help_text="Code of the integration", max_length=10, unique=True, verbose_name="Code"
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Integration",
                "verbose_name_plural": "Active Integrations",
            },
        ),
    ]
