# Generated by Django 4.2.7 on 2024-01-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0003_contract_cumplido_contract_idcontrato_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "IdOperac",
                    models.CharField(
                        blank=True, help_text="IdOperac", max_length=255, null=True, verbose_name="IdOperac"
                    ),
                ),
                (
                    "Numero",
                    models.CharField(blank=True, help_text="Numero", max_length=255, null=True, verbose_name="Numero"),
                ),
                (
                    "Fecha",
                    models.CharField(blank=True, help_text="Fecha", max_length=255, null=True, verbose_name="Fecha"),
                ),
                (
                    "FecContab",
                    models.CharField(
                        blank=True, help_text="FecContab", max_length=255, null=True, verbose_name="FecContab"
                    ),
                ),
                (
                    "FecVen",
                    models.CharField(blank=True, help_text="FecVen", max_length=255, null=True, verbose_name="FecVen"),
                ),
                (
                    "IdTercer",
                    models.CharField(
                        blank=True, help_text="IdTercer", max_length=255, null=True, verbose_name="IdTercer"
                    ),
                ),
                (
                    "IdActICA",
                    models.CharField(
                        blank=True, help_text="IdActICA", max_length=255, null=True, verbose_name="IdActICA"
                    ),
                ),
                (
                    "IdRetFte",
                    models.CharField(
                        blank=True, help_text="IdRetFte", max_length=255, null=True, verbose_name="IdRetFte"
                    ),
                ),
                (
                    "VlrRetFte",
                    models.FloatField(
                        blank=True, default=0, help_text="VlrRetFte", null=True, verbose_name="VlrRetFte"
                    ),
                ),
                (
                    "FechaCruce",
                    models.CharField(
                        blank=True, help_text="FechaCruce", max_length=255, null=True, verbose_name="FechaCruce"
                    ),
                ),
                (
                    "FactProvee",
                    models.CharField(
                        blank=True, help_text="FactProvee", max_length=255, null=True, verbose_name="FactProvee"
                    ),
                ),
                (
                    "FecEntrega",
                    models.CharField(
                        blank=True, help_text="FecEntrega", max_length=255, null=True, verbose_name="FecEntrega"
                    ),
                ),
                (
                    "CostoTtal",
                    models.FloatField(
                        blank=True, default=0, help_text="CostoTtal", null=True, verbose_name="CostoTtal"
                    ),
                ),
                (
                    "VrBruto",
                    models.FloatField(blank=True, default=0, help_text="VrBruto", null=True, verbose_name="VrBruto"),
                ),
                (
                    "VrDesc",
                    models.FloatField(blank=True, default=0, help_text="VrDesc", null=True, verbose_name="VrDesc"),
                ),
                (
                    "VrIva",
                    models.FloatField(blank=True, default=0, help_text="VrIva", null=True, verbose_name="VrIva"),
                ),
                (
                    "VrReteIva",
                    models.FloatField(
                        blank=True, default=0, help_text="VrReteIva", null=True, verbose_name="VrReteIva"
                    ),
                ),
                (
                    "VrReteIca",
                    models.FloatField(
                        blank=True, default=0, help_text="VrReteIca", null=True, verbose_name="VrReteIca"
                    ),
                ),
                (
                    "VrNeto",
                    models.FloatField(blank=True, default=0, help_text="VrNeto", null=True, verbose_name="VrNeto"),
                ),
                (
                    "VrBaseImp",
                    models.FloatField(
                        blank=True, default=0, help_text="VrBaseImp", null=True, verbose_name="VrBaseImp"
                    ),
                ),
                (
                    "Direccion",
                    models.CharField(
                        blank=True, help_text="Direccion", max_length=255, null=True, verbose_name="Direccion"
                    ),
                ),
                (
                    "FecMod",
                    models.CharField(blank=True, help_text="FecMod", max_length=255, null=True, verbose_name="FecMod"),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
            },
        ),
    ]
