apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-sicop
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/django

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-sicop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
