apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: local
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
status: {}
