# Generated by Django 4.2.7 on 2024-01-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="FecContab",
            field=models.DateTimeField(
                blank=True, help_text="Accountant date", null=True, verbose_name="Accountant date"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="FecMod",
            field=models.DateTimeField(
                blank=True, help_text="Modification date", null=True, verbose_name="Modification date"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="FecVen",
            field=models.DateTimeField(blank=True, help_text="Expiry date", null=True, verbose_name="Expiry date"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="Fecha",
            field=models.DateTimeField(blank=True, help_text="Date", null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="FechaCruce",
            field=models.DateTimeField(blank=True, help_text="Crossing date", null=True, verbose_name="Crossing date"),
        ),
    ]
