# Generated by Django 4.2.7 on 2024-01-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_order", "0002_alter_purchaseorder_feccontab_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="FecEntrega",
            field=models.DateTimeField(blank=True, help_text="Delivery date", null=True, verbose_name="Delivery date"),
        ),
    ]
