# Generated by Django 4.2.5 on 2023-10-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_unit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessunit",
            name="allocated_budget",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Allocated Budget",
                max_digits=20,
                verbose_name="Allocated Budget",
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="current_expenses",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current Expenses",
                max_digits=20,
                verbose_name="Current Expenses",
            ),
        ),
    ]
