# Generated by Django 4.2.5 on 2023-10-07 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_unit", "0002_businessunit_allocated_budget_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessunit",
            name="allocated_budget",
        ),
        migrations.RemoveField(
            model_name="businessunit",
            name="current_expenses",
        ),
    ]
