# Generated by Django 4.2.6 on 2023-10-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_unit", "0003_remove_businessunit_allocated_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessunit",
            name="code",
            field=models.SlugField(blank=True, help_text="Code", max_length=150, null=True, verbose_name="Code"),
        ),
    ]
