# Generated by Django 4.2.7 on 2023-11-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("area", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(help_text="Name", max_length=150, verbose_name="Name")),
                (
                    "project_id",
                    models.CharField(
                        blank=True, help_text="Project ID", max_length=150, null=True, verbose_name="Project ID"
                    ),
                ),
                ("description", models.CharField(help_text="Description", max_length=150, verbose_name="Description")),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Start date", null=True, verbose_name="Start date"),
                ),
                ("end_date", models.DateField(blank=True, help_text="End date", null=True, verbose_name="End date")),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget",
                        max_digits=12,
                        null=True,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "is_it_taxable",
                    models.BooleanField(default=False, help_text="Is it taxable", verbose_name="Is it taxable"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        help_text="Area",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="area.area",
                        verbose_name="Area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "code",
                    models.SlugField(blank=True, help_text="Code", max_length=150, null=True, verbose_name="Code"),
                ),
                ("name", models.CharField(help_text="Name", max_length=150, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Project Status",
                "verbose_name_plural": "Project Statuses",
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "code",
                    models.SlugField(blank=True, help_text="Code", max_length=150, null=True, verbose_name="Code"),
                ),
                ("name", models.CharField(help_text="Name", max_length=150, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Project Type",
                "verbose_name_plural": "Project Types",
            },
        ),
        migrations.CreateModel(
            name="ProjectStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                ("comment", models.TextField(blank=True, help_text="Comment", null=True, verbose_name="Comment")),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "project_status",
                    models.ForeignKey(
                        help_text="Project status",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projectstatus",
                        verbose_name="Project status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Status History",
                "verbose_name_plural": "Project Status Histories",
            },
        ),
    ]
