# Generated by Django 4.2.7 on 2023-11-16 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                help_text="Project manager",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project manager",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_status",
            field=models.ForeignKey(
                help_text="Project status",
                on_delete=django.db.models.deletion.CASCADE,
                to="project.projectstatus",
                verbose_name="Project status",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.ForeignKey(
                help_text="Project type",
                on_delete=django.db.models.deletion.CASCADE,
                to="project.projecttype",
                verbose_name="Project type",
            ),
        ),
    ]
