# Generated by Django 4.2.7 on 2023-11-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.FloatField(blank=True, default=0.0, help_text="Budget", null=True, verbose_name="Budget"),
        ),
    ]
