# Generated by Django 4.2.5 on 2023-09-27 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("area", "0004_rename_areamembers_areamember_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0002_projecttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="area",
            field=models.ForeignKey(
                default="",
                help_text="Area",
                on_delete=django.db.models.deletion.CASCADE,
                to="area.area",
                verbose_name="Area",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="is_it_taxable",
            field=models.BooleanField(default=False, help_text="Is it taxable", verbose_name="Is it taxable"),
        ),
        migrations.AddField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                default="",
                help_text="Project manager",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project manager",
            ),
            preserve_default=False,
        ),
    ]
