# Generated by Django 4.2.5 on 2023-09-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_project_area_project_is_it_taxable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.ForeignKey(
                default="",
                help_text="Project type",
                on_delete=django.db.models.deletion.CASCADE,
                to="project.projecttype",
                verbose_name="Project type",
            ),
            preserve_default=False,
        ),
    ]
