# Generated by Django 5.0 on 2023-12-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_project_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttype",
            name="cap",
            field=models.FloatField(default=0.0, help_text="Cap", verbose_name="Cap"),
        ),
    ]
