# Generated by Django 4.2.7 on 2023-12-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_projecttype_cap"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttype",
            name="redistribution_cap",
            field=models.FloatField(default=0.0, help_text="Redistribution Cap", verbose_name="Redistribution Cap"),
        ),
    ]
