# Generated by Django 4.2.6 on 2023-10-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_project_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttype",
            name="code",
            field=models.SlugField(blank=True, help_text="Code", max_length=150, null=True, verbose_name="Code"),
        ),
    ]
