# Generated by Django 4.2.7 on 2024-03-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_projecttype_redistribution_cap"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_closed",
            field=models.BooleanField(default=False, help_text="Is closed", verbose_name="Is closed"),
        ),
    ]
