# Generated by Django 4.2.7 on 2024-03-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_project_is_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="closed_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Closed datetime", null=True, verbose_name="Closed datetime"
            ),
        ),
    ]
