# Generated by Django 4.2.6 on 2023-10-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_projectstatus_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(
                blank=True, help_text="Project ID", max_length=150, null=True, verbose_name="Project ID"
            ),
        ),
    ]
