# Generated by Django 4.2.7 on 2024-03-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_project_closed_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_status",
            field=models.ForeignKey(
                help_text="Project status",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="project.projectstatus",
                verbose_name="Project status",
            ),
        ),
    ]
