# Generated by Django 4.2.6 on 2023-11-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_alter_project_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="Budget", max_digits=12, null=True, verbose_name="Budget"
            ),
        ),
    ]
