kind: PersistentVolume
apiVersion: v1
metadata:
  name: media
  namespace: local
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  namespace: local
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: media
