# Generated by Django 4.2.5 on 2023-10-03 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cost_center", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costcenter",
            name="cost_category",
        ),
    ]
