# Generated by Django 4.2.5 on 2023-10-04 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cost_center", "0002_remove_costcenter_cost_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CostCategory",
        ),
    ]
