# Generated by Django 4.2.6 on 2023-10-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cost_center", "0004_remove_costcenter_allocated_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcenter",
            name="cost_center_id",
            field=models.CharField(
                blank=True, help_text="Cost Center ID", max_length=150, null=True, verbose_name="Cost Center ID"
            ),
        ),
    ]
