# Generated by Django 4.2.6 on 2023-10-19 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cost_center", "0005_alter_costcenter_cost_center_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costcenter",
            name="area",
        ),
    ]
