from django.urls import path

from sicop.budget.views import (
    BudgetCapCreateView,
    BudgetCapDetailView,
    BudgetCapListView,
    BudgetCapUpdateView,
    BudgetCreateView,
    BudgetDescriptionCreateView,
    BudgetDescriptionDetailView,
    BudgetDescriptionListView,
    BudgetDescriptionUpdateView,
    BudgetDetailView,
    BudgetListView,
    BudgetProvisionCreate,
    BudgetUpdateView,
    GetBudgetsByCostCenter,
)

urlpatterns = [
    path(
        "description/list",
        BudgetDescriptionListView.as_view(),
        name="budget_description_list",
    ),
    path(
        "description/create/",
        BudgetDescriptionCreateView.as_view(),
        name="budget_description_create",
    ),
    path(
        "description/<int:pk>/",
        BudgetDescriptionDetailView.as_view(),
        name="budget_description_detail",
    ),
    path(
        "description/<int:pk>/update/",
        BudgetDescriptionUpdateView.as_view(),
        name="budget_description_update",
    ),
    path(
        "budget/list/",
        BudgetListView.as_view(),
        name="budget_list",
    ),
    path(
        "budget/<int:pk>/",
        BudgetDetailView.as_view(),
        name="budget_detail",
    ),
    path(
        "budget/create/",
        BudgetCreateView.as_view(),
        name="budget_create",
    ),
    path(
        "budget/<int:pk>/update/",
        BudgetUpdateView.as_view(),
        name="budget_update",
    ),
    path(
        "budget/cap/list/",
        BudgetCapListView.as_view(),
        name="budget_cap_list",
    ),
    path(
        "budget/cap/create/",
        BudgetCapCreateView.as_view(),
        name="budget_cap_create",
    ),
    path(
        "budget/cap/<int:pk>/",
        BudgetCapDetailView.as_view(),
        name="budget_cap_detail",
    ),
    path(
        "budget/cap/<int:pk>/update/",
        BudgetCapUpdateView.as_view(),
        name="budget_cap_update",
    ),
    path(
        "budget/cost_center/<int:pk>/",
        GetBudgetsByCostCenter.as_view(),
        name="get_budgets_by_cost_center",
    ),
    path(
        "budget/provision/create/",
        BudgetProvisionCreate.as_view(),
        name="budget_provision_create",
    ),
]
